/**
 * The text behind the admin Documentation page.
 *
 * It lives here rather than in the view because it is prose, not layout: the
 * page renders whatever sections this file exports, so adding a section is an
 * edit to this list and nothing else.
 *
 * `body` is markdown, rendered by `src/utils/markdown.ts` - the same renderer
 * the chat uses - so the subset that works there is the subset that works
 * here: headings up to `####`, lists, pipe tables, blockquotes, fenced code
 * blocks, `code`, **bold** and links.
 *
 * This file is the English edition and the canonical one: it fixes the section
 * order and the anchors. Every other language lives in a sibling file next to
 * it (`ru.ts`, `zh.ts`, ...) exporting the same two lists, and `docs/index.ts`
 * picks whichever matches the interface language.
 */

export type DocSection = {
  /** Anchor id, and what the table of contents links to. */
  id: string
  title: string
  body: string
}

/** A labelled cluster of sections in the table of contents. */
export type DocGroup = {
  label: string
  ids: string[]
}

/**
 * How the table of contents groups the sections.
 *
 * A flat list of twenty-one entries is a wall, so the rail shows a few labelled
 * clusters instead. The grouping is presentation, which is why it lives here as
 * a separate list rather than as a field on every section: reordering the
 * document does not mean editing twenty-one entries.
 *
 * A section missing from every group still renders; it simply falls into a
 * trailing group of its own.
 */
export const DOC_GROUPS: DocGroup[] = [
  {
    label: 'Getting started',
    ids: ['overview', 'quick-start', 'concepts'],
  },
  {
    label: 'How it works',
    ids: [
      'run-lifecycle',
      'building-a-project',
      'workflow',
      'agents',
      'skills',
      'tools',
      'context-tools',
      'storage',
      'memory',
      'delegation',
    ],
  },
  {
    label: 'Operating it',
    ids: ['chats', 'users-and-access', 'llm-connections', 'system-project'],
  },
  {
    label: 'Reference',
    ids: ['use-cases', 'security', 'operations', 'reference'],
  },
]

export const DOC_SECTIONS: DocSection[] = [
  {
    id: 'overview',
    title: 'Overview',
    body: [
      'CerebrumKit is a starting point for agentic projects. It gives you an admin panel where agents are built out of **skills** and **tools**, a storage library of business tables you can hand those agents, and a client panel where the people the project is for talk to them.',
      '',
      'Nothing here belongs to a particular business. There is no catalogue, no orders, no product table. What is here is the machinery every such project needs, so a new project starts at "what should the agents do" instead of at "how do I run an agent loop".',
      '',
      '## What you get',
      '',
      '| Piece | What it is |',
      '| --- | --- |',
      '| Projects | Group members, agents and the storage tables they may use, and hold the workflow that decides who answers a message |',
      '| Agents | A name, a description that is its system prompt, and the skills it carries |',
      '| Skills | Written instructions plus the tools they need |',
      '| Tools | An OpenAI function spec plus a Python body, both stored in the database |',
      '| Storage | Tables you create in the panel, with Excel import and export |',
      '| Chats | A websocket per chat that drives the agent loop and streams replies |',
      '| Memory | Notes an agent writes about a user, readable in that user\'s other chats |',
      '| Delegation | One agent hands a self-contained task to another agent in the project |',
      '| Users and roles | `admin` builds the projects, `client` only sees their own |',
      '| System project | A protected project holding a Project Manager agent that administers the install |',
      '',
      '## The idea in one paragraph',
      '',
      'A message arrives on a chat websocket. The agent loop reads the project workflow, picks the agent or group that should answer, builds the system prompt from the agent\'s description plus its skills plus any pre-run tool output, and calls the model. Tool calls come back as function calls; each is executed against the tool body stored in the database, with the project, chat, agent and user ids injected so a tool can only ever touch its own run. Results go back to the model, and the text it produces is broadcast to the chat.',
      '',
      'Because tool and skill definitions live in the database rather than in the code, editing one in the panel takes effect on the next run with no restart and no deploy.',
    ].join('\n'),
  },
  {
    id: 'quick-start',
    title: 'Quick start',
    body: [
      '## Requirements',
      '',
      '- Python 3.12+ and Node 20+',
      '- PostgreSQL, or SQLite for a quick look by leaving `DATABASE_URL` on its default',
      '',
      '## 1. Database',
      '',
      '```bash',
      'docker compose up -d              # or point DATABASE_URL at an existing server',
      'createdb cerebrumkit              # when you run Postgres yourself',
      '```',
      '',
      '## 2. Backend',
      '',
      '```bash',
      'cd backend',
      'python -m venv venv',
      'venv/Scripts/python.exe -m pip install -r requirements.txt      # Windows',
      '# source venv/bin/activate && pip install -r requirements.txt   # macOS / Linux',
      'cp .env.example .env              # then set DATABASE_URL, SECRET_KEY,',
      '                                  # DEEPSEEK_* and the SEED_* accounts',
      'venv/Scripts/python.exe seed_all.py',
      '```',
      '',
      '`seed_all.py` creates the tables, the country list, the admin and client accounts, the general tools and skills, and the System project with its Project Manager agent. Every step is idempotent, so running it again is safe.',
      '',
      'It also copies `DEEPSEEK_*` into the `platforms` table, which is what the system actually runs on. After that, **Settings -> LLM Connections** is the place to change provider, base URL, API key or model.',
      '',
      '## 3. Frontend',
      '',
      '```bash',
      'cd ../frontend/cerebrumkit-vue',
      'npm install',
      'npm run dev',
      '```',
      '',
      'On Windows you can also double-click `run.ps1`, which starts both servers; `stop.ps1` stops them.',
      '',
      '## 4. Sign in',
      '',
      'Open <http://localhost:5173> and sign in with the `SEED_ADMIN_EMAIL` / `SEED_PASSWORD` you set in `backend/.env`.',
      '',
      '> Change the seeded passwords before anyone else can reach the install.',
      '',
      '## 5. Point it at a model',
      '',
      'Open **Settings -> LLM Connections**. The connection the seeder copied from `.env` is already active and marked **In use**. Press **Test** on it: that makes one small real call, so a wrong URL, key or model name surfaces here instead of in the middle of a run.',
      '',
      '## 6. First chat',
      '',
      'Open **Projects**, pick the **System** project, open a chat and ask the Project Manager something. If it answers, the install is working end to end.',
      '',
      'To build your own thing, follow **Building a project** below. Or ask the Project Manager to do it for you: that is the point of the System project.',
    ].join('\n'),
  },
  {
    id: 'concepts',
    title: 'Core concepts',
    body: [
      'Everything else in this page is a detail of one of these.',
      '',
      '| Concept | What it is |',
      '| --- | --- |',
      '| **Project** | The unit of work. Owns a workflow, a set of member users, a set of agents, and a set of storage tables. |',
      '| **Agent** | A name, a description that becomes its system prompt, and the skills it carries. Answers chats in the projects it belongs to. |',
      '| **Skill** | A written instruction block, plus the tools that instruction needs. Attaching a skill to an agent gives it those tools. |',
      '| **Tool** | A function spec (what the model sees) plus a Python body (what actually runs). Both are rows in the database. |',
      '| **Context tool** | A tool an agent runs *before* it reads the message, whose output is placed in its system prompt. |',
      '| **Workflow** | The start / group / stop graph that decides which agents answer a message, in what order. |',
      '| **Storage table** | A real database table created from the panel, with a description on the table and on each column. |',
      '| **Chat** | One conversation between a user and a project\'s agents, driven over a websocket. |',
      '| **Memory** | A note an agent writes about a user, keyed by (agent, user) so it is readable across that user\'s chats. |',
      '| **LLM connection** | A row in `platforms`: base URL, API key, model, temperature, max tokens, thinking. One is active. |',
      '| **System project** | The one project that cannot be renamed or deleted. Holds the Project Manager. |',
    ].join('\n'),
  },
  {
    id: 'run-lifecycle',
    title: 'How a message becomes an answer',
    body: [
      'This is the whole loop, in order. Every step names the file that does it.',
      '',
      '1. **The user sends a message** on the chat websocket (`backend/app/routers/websocket.py`). The token is verified, and the user must actually own the chat - a valid token alone is not enough. The message is handed to the agent loop as a background task, so a run never blocks the socket.',
      '2. **The loop loads the project workflow** (`backend/app/core/agent_loop.py`). It finds the `start` node, then walks the graph. A run is capped at 200 steps as a safety net against a malformed or cyclic workflow.',
      '3. **A group node runs its agents**, one at a time, in the order they were assigned. Missing agents are skipped with a warning rather than spending a call on nothing.',
      // Written as one flat step rather than a nested list: the renderer builds
      // lists from lines that start at column zero, so an indented sub-bullet
      // would break the surrounding numbering.
      '4. **Each agent\'s prompt is assembled** from four things: `You are {name}. {description}`, where the description *is* the agent\'s standing brief; the output of its **context tools**, run right now, each under its own heading (capped at 24,000 characters in total); the agent\'s **own last reply** in this chat, placed as the turn before the new one so a follow-up continues earlier work instead of restarting cold (tail of 2,000 characters); and the incoming message.',
      '5. **The model is called** through the system\'s active LLM connection. The client is reused while the configuration behind it is unchanged, because rebuilding one throws away its HTTP connection pool.',
      '6. **Tool calls are executed.** Each is checked against the project, chat, agent and tool before it runs, then the body is compiled and called with `project_id`, `chat_id`, `agent_id`, `user_id` and `call_depth` already in scope (`backend/app/core/tool_exec.py`).',
      '7. **Results go back to the model.** A result over 8,000 characters is trimmed *inside* its JSON rather than cut off, because half a JSON object makes a model re-issue the same call instead of answering. The full result is still kept on the tool card in the chat.',
      '8. **The reply is saved and broadcast.** Tool calls appear as their own cards in the transcript, and the agent\'s text streams into the conversation.',
      '9. **The next node runs** with the previous group\'s combined output as its input. The last group answers the user.',
      '',
      'A run can be stopped mid-flight from the client; the task is cancelled and the chat returns to idle.',
      '',
      '## What the agent does and does not see',
      '',
      '- It does **not** get the earlier chat transcript (`HISTORY_WINDOW` is `0`).',
      '- It **does** get its own previous reply, plus anything its context tools fetch, plus whatever tools return during the run.',
      '- Cross-chat recall is what **memory** is for: an agent writes a note with `memory_write` and reads it back with `memory_lookup` in any later chat with the same user.',
      '',
      'That shape is deliberate. An unbounded transcript crowds out the tools and the current request, and usually the agent needs a *fact it learned*, not the wording of the conversation.',
    ].join('\n'),
  },
  {
    id: 'building-a-project',
    title: 'Building a project',
    body: [
      'Either build it in the panel (**Projects -> Create Project**), or ask the Project Manager in the System project\'s chat to do it for you. The order that works:',
      '',
      '1. **Storage** - create the tables the project owns, with a description on the table and on each column. Tools read these, and the agent sees the descriptions.',
      '2. **Tools** - one per thing an agent should be able to do. Write the Python body if you know it, or describe the tool and let the generator draft the spec.',
      '3. **Skills** - group the tools under written instructions: when to use them, what to pass, how to read the result.',
      '4. **Agents** - a description that is the agent\'s standing brief, plus the skills it carries. Optionally, tools to run before every message.',
      '5. **Project** - assign the tables, add the agents, and wire the workflow so messages reach them.',
      '6. **Users** - create client accounts and add them to the project. They see only their own projects and chats.',
      '',
      'Two habits that pay off:',
      '',
      '- **Write the descriptions as if for a new colleague.** The table, column, tool and skill descriptions are the only thing the model knows about your data. "Customer lifetime value in EUR, updated nightly" is worth ten lines of code; "a number" is worth nothing.',
      '- **Give an agent one job.** An agent with four skills and twenty tools is worse at all of them than four agents with one each, because every tool description is competition for the model\'s attention.',
    ].join('\n'),
  },
  {
    id: 'workflow',
    title: 'The workflow',
    body: [
      'The workflow is a small graph stored on the project as JSON. It has three kinds of node:',
      '',
      '| Node | What it does |',
      '| --- | --- |',
      '| `start` | Where a message enters. Exactly one. |',
      '| `group` | Runs the agents assigned to it, one after another, in order. |',
      '| `stop` | Ends that path. |',
      '',
      '`wires` connect them. A group\'s combined output is passed to whatever node follows, so a second group sees the first group\'s work as its input. The **final** group\'s output is what the user is answered with.',
      '',
      '```json',
      '{',
      '  "nodes": [',
      '    { "id": 1, "type": "start", "label": "Start" },',
      '    { "id": 2, "type": "group", "label": "Default Group",',
      '      "agents": [ { "id": 1, "name": "Project Manager" } ] },',
      '    { "id": 3, "type": "stop", "label": "Stop" }',
      '  ],',
      '  "wires": [',
      '    { "id": "1-out->2-in", "fromNode": 1, "fromPort": "1-out", "toNode": 2, "toPort": "2-in" },',
      '    { "id": "2-out->3-in", "fromNode": 2, "fromPort": "2-out", "toNode": 3, "toPort": "3-in" }',
      '  ]',
      '}',
      '```',
      '',
      '## Chaining agents',
      '',
      'Two groups wired in sequence is how you build a pipeline: a research agent that gathers, then a writing agent that drafts, then a review agent that checks. Each group sees what the one before it produced.',
      '',
      'Keep chains short. Every group is a full model round-trip with its own tool budget, so a five-stage chain is five chances to lose the thread and five times the latency.',
    ].join('\n'),
  },
  {
    id: 'agents',
    title: 'Agents',
    body: [
      'An agent is a name, a description and a set of skills.',
      '',
      '**The description is the system prompt.** It is not documentation. Write it as a standing brief: who this agent is, what it is responsible for, how it should behave, what it should refuse. The loop wraps it as `You are {name}. {description}` and appends a short instruction to be helpful, concise and economical with tools.',
      '',
      '**Skills bring the tools.** An agent has no direct tool list; it has skills, and each skill carries tools. That is why adding a capability means attaching a skill rather than ticking twelve checkboxes.',
      '',
      '**Context tools** (optional) are tools the agent runs on its own before it reads the message. Use them for what is knowable in advance and always needed - the current date, the user\'s profile, a product catalogue. Each result is placed in the system prompt under a heading you write. See **Context tools** below.',
      '',
      '**Active** is an off-switch only: an inactive agent is skipped and its skills are not usable through it.',
      '',
      '## A good description',
      '',
      '```text',
      'You are the support agent for an online store. You answer questions about',
      'orders, delivery and returns. Look orders up with order_lookup - never ask',
      'the customer for an order id you can find from their account. If a refund is',
      'requested, check the return window before promising anything. If the request',
      'is about a product you cannot see in the catalogue, say so and offer to pass',
      'it to a colleague.',
      '```',
      '',
      'Note what it does: names the tools, states the boundaries, and says what to do when stuck. A description of "helpful support agent" produces a helpful agent that invents order numbers.',
    ].join('\n'),
  },
  {
    id: 'skills',
    title: 'Skills',
    body: [
      'A skill is a written instruction plus the tools that instruction needs. Give an agent the skill and the tools come with it.',
      '',
      'Skill text is markdown and is placed in the agent\'s system prompt. It is the place for the procedural knowledge that does not fit in the agent description:',
      '',
      '- **When to use this skill** - the trigger, so the agent picks it at the right moment.',
      '- **Instructions** - the steps, in order.',
      '- **Examples** - a call and the shape of a good result.',
      '- **Notes and pitfalls** - the mistake the agent would otherwise make every time.',
      '',
      'The seeded skills are good models to copy. **"System Administration"** bundles the manage tools with the rules for using them; **"Delegate a Self-Contained Task to Another Agent"** is a full worked example of the format.',
      '',
      'Skills are reusable across agents and projects. If two agents need the same procedure, write it once.',
    ].join('\n'),
  },
  {
    id: 'tools',
    title: 'Tools',
    body: [
      'A tool has two halves, both stored on the tool row:',
      '',
      '| Field | What it holds |',
      '| --- | --- |',
      '| `description` | The OpenAI function spec as JSON - the name, the description the model reads, and the parameters |',
      '| `body` | The Python that runs, defining a function with the same name as the spec |',
      '',
      'The panel\'s **Generate** button drafts both from a plain-English description, using the model configured in Settings. Review what it writes - especially a body, see the security note below.',
      '',
      '## The function spec',
      '',
      '```json',
      '{',
      '  "type": "function",',
      '  "function": {',
      '    "name": "order_lookup",',
      '    "description": "Look up one order by its id. Returns status, items and delivery date.",',
      '    "parameters": {',
      '      "type": "object",',
      '      "properties": {',
      '        "order_id": { "type": "integer", "description": "The order id." }',
      '      },',
      '      "required": ["order_id"]',
      '    }',
      '  }',
      '}',
      '```',
      '',
      'Write the description for the model, not for a human: say what it returns, and say what it does *not* do so the model does not reach for it by mistake.',
      '',
      '## The body',
      '',
      'The body defines a function whose name must match `function.name`. It runs with the run\'s ids already in scope:',
      '',
      '| Variable | What it is |',
      '| --- | --- |',
      '| `project_id` | The project the run belongs to |',
      '| `chat_id` | The chat the run belongs to |',
      '| `agent_id` | The agent that called the tool |',
      '| `user_id` | The **owner of the chat** - not whoever typed, since an admin can post into another user\'s chat |',
      '| `call_depth` | `0` for a run a person started, `1` for a delegated run, and so on |',
      '',
      'These are supplied by the server and must never be declared as parameters - a model that could pass `project_id` could read any project.',
      '',
      '```python',
      'def order_lookup(order_id: int):',
      '    from app.core.database import SessionLocal',
      '    from sqlalchemy import text',
      '',
      '    db = SessionLocal()',
      '    try:',
      '        row = db.execute(',
      '            text("SELECT id, status, delivered_at FROM orders "',
      '                 "WHERE id = :oid AND project_id = :pid"),',
      '            {"oid": order_id, "pid": project_id},',
      '        ).mappings().first()',
      '        if row is None:',
      '            return f"No order {order_id} in this project."',
      '        return dict(row)',
      '    finally:',
      '        db.close()',
      '```',
      '',
      'Two rules that keep tools reliable:',
      '',
      '- **Return a sentence, not an exception.** A raised error becomes a string the model reads; a caught one lets you say *why* it failed.',
      '- **Scope every query to the run.** Filter by `project_id` (and the user) so a tool can only ever touch data it was given.',
      '',
      '> **Security.** A tool body is arbitrary Python, compiled and executed with full builtins. It is deliberately not sandboxed, because the shipped tools import `requests`, SQLAlchemy and app internals. The consequence is that authoring a tool is equivalent to running code on the server: keep the admin endpoints admin-only, and review a generated body the way you would review source code.',
    ].join('\n'),
  },
  {
    id: 'context-tools',
    title: 'Context tools',
    body: [
      'Some of what an agent needs is knowable before the message is read: the environment it runs in, the user\'s profile, the catalogue it works against. Those lookups do not depend on the wording of the message, so leaving them to the model costs a tool round and is skipped whenever the model decides it already knows enough.',
      '',
      'A **context tool** makes that lookup part of how the agent starts. The tool runs, and its output is placed in the agent\'s system prompt under the heading you write.',
      '',
      'Only a tool the agent already has - through a skill - can be chosen. For each one you set:',
      '',
      '| Setting | Meaning |',
      '| --- | --- |',
      '| Comment | The heading written above the output, so the agent is told what it is looking at |',
      '| Arguments | A JSON object of arguments, for a tool that needs them; empty for one that takes none |',
      '| Order | Which appears first in the prompt |',
      '',
      'The whole block is capped at 24,000 characters. An entry that no longer fits is dropped and counted rather than cut in half, because half a JSON object invites the model to call the tool again to fill the gap.',
      '',
      'Use context tools sparingly. They run on **every** message, so a slow one adds its latency to every turn, and a large one competes with the actual request for the model\'s attention.',
    ].join('\n'),
  },
  {
    id: 'storage',
    title: 'Storage',
    body: [
      'Storage is a library of business tables you create from the panel, without writing a migration. Each table is a real table in the database.',
      '',
      'A table carries:',
      '',
      '- A **name**, and a **description** the agent can read.',
      '- **Columns**, each with a type and a description.',
      '- A set of **projects** it is assigned to. A tool can only reach a table its project owns.',
      '',
      'Columns are added and altered from the panel, and the underlying table is changed to match. Rows can be edited by hand, and a table can be **imported from** and **exported to** Excel - import previews the first rows so you can see the mapping before committing.',
      '',
      '## Why the descriptions matter',
      '',
      'The agent never sees your schema. It sees the table description and the column descriptions, and decides from those whether and how to query. A table called `t1` with a column called `val` is invisible to it. `customer_orders` with `delivered_at - when the parcel reached the customer; NULL while in transit` is usable.',
      '',
      '## Where it fits',
      '',
      'Give a project its tables, then write tools that read and write them. This is the usual shape of a real project: the business data lives in storage, and the tools are the verbs the agent is allowed to perform on it.',
      '',
      'Tables created outside the panel (by adding a SQLAlchemy model and running `migrate.py`) can also be assigned to a project from the storage screen.',
    ].join('\n'),
  },
  {
    id: 'memory',
    title: 'Memory',
    body: [
      'Memory is how an agent remembers a fact about a person between chats.',
      '',
      'A note is keyed by **(agent, user)**, not by chat. So a note the support agent writes in Monday\'s chat is readable by the same agent in Friday\'s chat - and not readable by a different agent, which matters because agents have different jobs and different things worth remembering.',
      '',
      'Two tools do the work:',
      '',
      '| Tool | What it does |',
      '| --- | --- |',
      '| `memory_write` | Save or update a note about the current user |',
      '| `memory_lookup` | Read back what is known about the current user |',
      '',
      'Both come with the seeded **"Context & Memory Awareness"** skill. Attach it to any agent that should carry knowledge forward.',
      '',
      'Memory is not a transcript. It is for durable facts - a preference, a constraint, an outstanding issue - and the agent decides what is worth keeping. For the conversation itself, the agent has its own last reply; for everything else, it queries.',
    ].join('\n'),
  },
  {
    id: 'delegation',
    title: 'Delegation',
    body: [
      'An agent can hand a self-contained task to another agent in the same project and use the answer.',
      '',
      'The tool is `call_agent`, and it ships in the seeded skill **"Delegate a Self-Contained Task to Another Agent"** - which is also the best documentation of the pattern, so read it in the Skills screen.',
      '',
      'The important property: **the other agent sees nothing of your conversation.** Not the user\'s message, not your tools, not what you found. The `message` you pass must therefore carry the whole request - background, deliverable, constraints, expected format.',
      '',
      'Guards that keep it sane:',
      '',
      '- Delegation may go **3 agents deep**. Two agents that call each other stop instead of looping forever.',
      '- A delegated run gets a smaller tool budget (**8 rounds**) than a run a person started, because it has to answer inside its caller\'s turn.',
      '- A delegated run that does not finish in time returns a sentence explaining that, which the caller reads like any other tool result.',
      '',
      'Delegation is not a privilege - it is not part of system administration. Any agent in a project can usefully hand work to another, so give the skill to whoever needs it.',
    ].join('\n'),
  },
  {
    id: 'chats',
    title: 'Chats and the client panel',
    body: [
      'A chat belongs to one user and one project. Its websocket is what drives the loop: the client sends a message, and the server streams back status, typing indicators, tool cards and replies.',
      '',
      'In the transcript you will see:',
      '',
      '- The **user message**, once.',
      '- A **tool card** per tool call, with the input and the output - so a wrong answer can be traced to the call that produced it.',
      '- **Flow messages**: when one agent\'s output becomes another\'s input, that hand-off is recorded too. They are marked as flow rather than shown as if a person typed them.',
      '- The **agent\'s reply**.',
      '',
      'A run can be **stopped** mid-flight; the chat returns to idle and the partial work already saved stays in the transcript.',
      '',
      '## The client panel',
      '',
      'Clients see **their own projects and chats, and nothing else**. They cannot see the tools, the skills, the workflow or the storage tables behind what they are using - only the conversation. That separation is the point: an operator can rebuild the whole agent stack underneath without the people using it noticing anything but better answers.',
    ].join('\n'),
  },
  {
    id: 'users-and-access',
    title: 'Users, roles and access',
    body: [
      'There are two roles.',
      '',
      '| Role | Can do |',
      '| --- | --- |',
      '| `admin` | Everything: projects, agents, skills, tools, storage, users, LLM connections. Sees every chat. |',
      '| `client` | Their own projects and their own chats. Nothing else. |',
      '',
      'Users are created in **Users** (or by the Project Manager in chat). A client only reaches a project they have been added to.',
      '',
      'Access rules worth knowing:',
      '',
      '- **Public self-registration always creates a client.** The role is taken from the server, never from the request body - otherwise anyone could mint an admin account.',
      '- **Elevated roles are only granted through the admin endpoints.**',
      '- **A chat belongs to its owner.** A non-admin cannot post into someone else\'s chat, subscribe to it, or cancel its run.',
      '- **Anonymous requests get 401, wrong role gets 403.** Every admin router is guarded at the router level, so no individual endpoint can forget it.',
      '- **Sign-in and registration are rate-limited.**',
      '',
      '> An administrator *can* post into a client\'s chat. When that happens, the run still acts for the chat\'s owner - `user_id` in a tool is the owner, not the admin who typed.',
    ].join('\n'),
  },
  {
    id: 'llm-connections',
    title: 'LLM connections',
    body: [
      'The model the whole system runs on is a row in the `platforms` table, not a value in a config file. That makes changing provider, base URL, key or model a data change an admin can make from the panel instead of a deploy.',
      '',
      '**Settings -> LLM Connections** manages them. Each row holds:',
      '',
      '| Field | Meaning |',
      '| --- | --- |',
      '| Name | A label, so you can tell two rows apart |',
      '| Base URL | The API endpoint (blank uses the provider default) |',
      '| API key | The credential, stored and shown as entered |',
      '| Model | The model name to request |',
      '| Temperature | `0`-`2`; blank leaves it to the provider |',
      '| Max tokens | Upper bound on the reply; blank means no limit |',
      '| Thinking | Ask a reasoning model to think before answering |',
      '',
      '## How one is chosen',
      '',
      '1. The row marked **active** is used.',
      '2. If nothing is active, the **first** row is used.',
      '3. If the table is empty, the `DEEPSEEK_*` values in `.env` are used - which is what a brand-new install has before anything has been saved.',
      '',
      'Exactly one row is active at a time: activating one clears the others. The banner at the top of the page always shows which connection is actually in effect, so you never have to apply the fallback rule yourself.',
      '',
      '## Testing',
      '',
      '**Test** makes one small real call against that row and reports what came back. It is the fastest way to check a key, a URL or a model name - and it is worth pressing after any edit, because a bad connection otherwise shows up as a failed run much later.',
      '',
      'Saving an edit takes effect on the **next run**, with no restart. Clients are reused while the configuration behind them is unchanged, so switching providers does not throw away connection pools for no reason.',
      '',
      '> The API key is stored as entered and returned as entered - it is not masked. The Settings screen is admin-only for exactly that reason: anyone who can read the list can spend against the account behind it.',
    ].join('\n'),
  },
  {
    id: 'system-project',
    title: 'The System project and the Project Manager',
    body: [
      'One project is special. It is marked `is_system`, which means its own row cannot be renamed or deleted - so the agent that lives in it always has a home. Everything *inside* it stays editable, and that is what makes the arrangement work.',
      '',
      'It holds the **Project Manager** agent, carrying the **"System Administration"** skill and the delegation skill. Its tools are:',
      '',
      '| Tool | What it manages |',
      '| --- | --- |',
      '| `manage_users` | List, get, create, update, activate/deactivate users |',
      '| `manage_projects` | Projects, their members, their agents, and their workflow |',
      '| `manage_agents` | Agents and the skills they carry |',
      '| `manage_skills` | Skills and the tools they carry |',
      '| `manage_tools` | Tools, including generating a spec and body from a description |',
      '| `manage_storage` | Storage tables, their columns, and their rows |',
      '| `call_agent` | Hand a task to another agent in the project |',
      '',
      'So the install can be administered by **asking it in chat**. Create a user, stand up a project, write a tool, wire a workflow - the Project Manager does it through the same service layer the panel uses, not through the REST API.',
      '',
      'It is also the fastest way to learn the system: ask it what exists, and watch which tool calls come back.',
      '',
      'Guards worth knowing: the Project Manager cannot delete the System project, cannot remove itself from it, and cannot strip its own home project or its own skills - so you cannot accidentally lock yourself out of administration.',
    ].join('\n'),
  },
  {
    id: 'use-cases',
    title: 'Use cases',
    body: [
      'CerebrumKit is a starting point, so these are shapes rather than finished products. Each one is the same machinery with a different storage library and a different set of tools.',
      '',
      '## 1. A support desk that answers from your own data',
      '',
      '**Storage** holds `customers`, `orders` and `articles`. **Tools** look an order up by id, find a customer by email, and search the help articles. A support agent carries a skill that tells it: identify the customer first, never quote a delivery date you have not read from the order, and escalate anything about a refund.',
      '',
      'The client panel is your support inbox. The valuable part is the tool descriptions and the skill text, not the model: a generic model plus your order table beats a great model with no data.',
      '',
      '## 2. An operations console over a business system',
      '',
      'Your real data lives in another system behind an HTTP API. The seeded **`api_call`** tool makes requests; write thin tools per endpoint - `get_invoice`, `list_open_tickets`, `approve_leave` - so the agent works with named verbs instead of raw URLs.',
      '',
      'Two agents chained in the workflow: one gathers and summarises, one drafts the action. A human reads the draft in the chat before anything is approved. Read-only tools first; add the write paths once you trust the descriptions.',
      '',
      '## 3. Inside sales: research before the call',
      '',
      'A research agent with a `web_search` skill and a `company_lookup` tool over an `accounts` table. Its **context tool** pre-loads the account record before every message, so "what should I open with?" is answered against real data instead of being asked for.',
      '',
      'Delegation earns its keep here: the primary agent hands "summarise the last two quarters" to a research agent and uses the answer, without the research agent seeing the whole thread.',
      '',
      '## 4. Back-office document intake',
      '',
      'Operators paste or upload extracted document text into a chat. Tools match it against reference tables in storage and propose the ledger entries. An approval queue is just a second project whose agent is allowed to write.',
      '',
      'The Excel import on a storage table is how the reference data gets in; the export is how a reviewer takes the result away.',
      '',
      '## 5. A productised assistant for your own customers',
      '',
      'One project per customer, each with its own storage tables and its own agents, and client accounts scoped to their own project. The admin panel is your back office; the client panel is the product.',
      '',
      'Because a client sees only their own chats and never the tools or tables behind them, you can rebuild an agent\'s skills between sessions without the customer noticing anything except the answers changing.',
      '',
      '## 6. Administer the platform by talking to it',
      '',
      'Even with no business domain at all, the System project is useful: ask the Project Manager to create a user, stand up a project, write a tool from a description, attach it to a skill and wire it into a workflow. Then read the tool cards in the transcript to see exactly what it did.',
      '',
      'For anyone learning the system, this is the fastest possible tour - and it is a working example of the whole design.',
    ].join('\n'),
  },
  {
    id: 'security',
    title: 'Security and trust',
    body: [
      'The trust model is worth stating plainly, because two of its properties are deliberate and one of them is sharp.',
      '',
      '## A tool body is code execution',
      '',
      'Tool bodies are compiled and executed with full builtins. They are **not sandboxed**, because the shipped tools import `requests`, SQLAlchemy and app internals, and one passes model-authored SQL to the database - a restricted-builtins sandbox would break all of them.',
      '',
      'So: authoring a tool is equivalent to running code on the server. The admin tool endpoints must stay admin-only, and `tools.body` should be reviewed the way you would review a commit. This is also why the **Generate** button drafts a body but does not install it silently.',
      '',
      'A caller still cannot reach a tool that is not attached to their agent, and a tool body cannot be handed a `project_id` by the model - the server supplies the run\'s own ids.',
      '',
      '## Access control',
      '',
      '| Rule | Where it is enforced |',
      '| --- | --- |',
      '| Admin routers are admin-only | Router-level dependency, so no endpoint can forget |',
      '| Registration cannot mint an admin | The role is set server-side, never read from the body |',
      '| A chat belongs to its owner | Checked on the REST routes and again on the websocket |',
      '| Chat history cannot be read across users | Non-admins are always filtered to their own rows |',
      '| Sign-in and registration are rate-limited | Sliding-window limiter keyed per client |',
      '',
      '## Credentials',
      '',
      '- LLM API keys are stored in the database and shown **unmasked** in Settings, which is admin-only by design.',
      '- `SECRET_KEY` signs the JWTs. The app warns on startup when it is left at the example value - change it before anyone else can reach the install.',
      '- The seeded accounts have seeded passwords. Change them.',
      '- `.env` is not committed. Keep it that way.',
      '',
      '## Where model output is treated as untrusted',
      '',
      '- Spreadsheet export neutralises formula injection, so a cell beginning `=` cannot run in Excel.',
      '- Tool results are truncated before they reach the model, and trimmed inside their JSON rather than cut.',
      '- Workflow runs are capped in steps, tool rounds, delegation depth and tool duration, so no single run can spin forever.',
    ].join('\n'),
  },
  {
    id: 'operations',
    title: 'Operations',
    body: [
      '## Running it',
      '',
      '```bash',
      '# backend',
      'cd backend && venv/Scripts/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8000',
      '',
      '# frontend',
      'cd frontend/cerebrumkit-vue && npm run dev',
      '```',
      '',
      'On Windows, `run.ps1` starts both and `stop.ps1` stops them. For production, `DEPLOY.md` covers nginx, systemd, and a rebuild path that keeps the database rows (tools, skills, agents) in step with the code.',
      '',
      '## Database changes',
      '',
      '`backend/migrate.py` creates any missing tables and adds missing columns. It is safe to re-run: it is how a new install is brought up, and how a new model in `backend/app/models/` is turned into a table.',
      '',
      '## Seeding',
      '',
      '| Script | What it does |',
      '| --- | --- |',
      '| `seed_all.py` | Everything below, in order - the one command a fresh install needs |',
      '| `seed.py` | Admin and client accounts from the `SEED_*` variables |',
      '| `seed_countries.py` | The country list |',
      '| `seed_general_tools.py` | The general tools and their skills |',
      '| `seed_system_project.py` | The System project and the Project Manager |',
      '',
      'All of them are idempotent - rows are matched by name and updated in place - so re-running after editing a tool body pushes the fix.',
      '',
      '## Moving data between installs',
      '',
      '`export_for_deploy.py` writes the project data out and `load_for_deploy.py` reads it in. Use them to move tools, skills, agents and storage definitions from a development install to a deployed one.',
      '',
      '## Logs',
      '',
      'The `run.ps1` helper writes `backend.log` / `backend.err.log` and `frontend.log` / `frontend.err.log` beside the project root. A failed run is logged with the chat id, so a report of "it did not answer" can be traced to the run that failed.',
      '',
      '## Deploying a change to agents',
      '',
      'Most agent changes need no deploy at all: edit the tool, skill or agent in the panel and it takes effect on the next run. You only redeploy when the **code** changes - the agent loop, a router, a model.',
    ].join('\n'),
  },
  {
    id: 'reference',
    title: 'Reference',
    body: [
      '## Limits',
      '',
      'Every cap exists to stop one runaway run from consuming the system. They live in `backend/app/core/agent_loop.py`.',
      '',
      '| Limit | Value | Why |',
      '| --- | --- | --- |',
      '| Tool-call rounds per agent turn | 100 | Stops a model looping on tool calls |',
      '| Tool-call rounds in a delegated run | 8 | It must answer inside its caller\'s turn |',
      '| Delegation depth | 3 | Two agents calling each other stop |',
      '| Tool call timeout | 60 s | A tool that never returns cannot hang the run |',
      '| Delegation call timeout | 300 s | A nested run needs longer than a normal tool |',
      '| Tool result handed to the model | 8,000 chars | One large API response cannot eat the context window |',
      '| Tool card kept in the chat | 100,000 chars | The card is for a person, and is still bounded |',
      '| Pre-run context tools, total | 24,000 chars | Keeps the system prompt in proportion |',
      '| Agent\'s own last reply injected | 2,000 chars | Enough for the conclusion, not a whole page of JSON |',
      '| Workflow steps per run | 200 | Safety net for a malformed or cyclic workflow |',
      '| Earlier chat messages sent to the agent | 0 | Tools and memory carry the facts, not the transcript |',
      '| Model call timeout | 180 s | Per call, per agent |',
      '',
      '## Tables',
      '',
      '| Table | Holds |',
      '| --- | --- |',
      '| `users` | Accounts, roles, language, country |',
      '| `projects` | Projects, their workflow JSON, and the `is_system` flag |',
      '| `agents` | Agents and their descriptions |',
      '| `skills` | Skills and their instruction text |',
      '| `tools` | Tools: function spec (`description`) and Python body (`body`) |',
      '| `agent_skill`, `skill_tool` | Which skills an agent has, which tools a skill has |',
      '| `user_project`, `agent_project` | Project membership |',
      '| `agent_context_tools` | Pre-run tools, their headings and arguments |',
      '| `chats`, `messages` | Conversations and every message in them, tool cards included |',
      '| `memory` | Notes keyed by (agent, user) |',
      '| `project_tables` | Which storage tables a project owns |',
      '| `platforms` | LLM connections, and which one is active |',
      '| `countries` | The country list |',
      '',
      'Tables you create in **Storage** are real tables too, and appear here alongside the ones above.',
      '',
      '## Where things live',
      '',
      '```text',
      'backend/app/core/       agent loop, tool execution, delegation, LLM client, auth',
      'backend/app/models/     SQLAlchemy models',
      'backend/app/routers/    REST + websocket API',
      'backend/app/schemas/    request/response models',
      'backend/app/system_management.py   the manage_* tools the Project Manager uses',
      'frontend/.../views/admin/    Projects, Skills, Tools, Storage, Users, Settings, Docs',
      'frontend/.../views/client/   Projects and the chat with the agents',
      'frontend/.../locales/        en, zh, ru, es, fr, de',
      '```',
      '',
      '## Adding a business domain',
      '',
      'Add models under `backend/app/models/`, register them in `app/models/__init__.py`, add routers and schemas the same way, and create the tables with `backend/migrate.py`.',
      '',
      'But prefer the storage library. Anything a project needs at runtime is better as a **tool over storage**, because then the people who own the project can change it without a deploy - which is the whole reason the tools and skills live in the database.',
    ].join('\n'),
  },
]
