/**
 * Die deutsche Ausgabe der Dokumentation.
 *
 * Gleiche Form wie `content.ts`: `DOC_GROUPS` beschriftet die Gruppen des
 * Inhaltsverzeichnisses, `DOC_SECTIONS` liefert einen Eintrag je Anker. Die
 * `id`-Werte bleiben englisch — sie sind der Vertrag mit `docs/index.ts` und
 * die Adressen wie `#doc-overview`, dürfen also nicht übersetzt werden.
 */
import type { DocGroup, DocSection } from './content'

export const DOC_GROUPS: DocGroup[] = [
  { label: 'Erste Schritte', ids: ['overview', 'quick-start', 'concepts'] },
  {
    label: 'Wie es funktioniert',
    ids: [
      'run-lifecycle',
      'building-a-project',
      'workflow',
      'agents',
      'skills',
      'tools',
      'context-tools',
      'storage',
      'memory',
      'delegation',
    ],
  },
  {
    label: 'Betrieb',
    ids: ['chats', 'users-and-access', 'llm-connections', 'system-project'],
  },
  { label: 'Referenz', ids: ['use-cases', 'security', 'operations', 'reference'] },
]

export const DOC_SECTIONS: DocSection[] = [
  {
    id: 'overview',
    title: 'Überblick',
    body: [
      'CerebrumKit ist ein Ausgangspunkt für agentische Projekte. Es liefert ein Admin-Panel, in dem Agenten aus **Fähigkeiten** und **Werkzeugen** zusammengesetzt werden, eine Speicher-Bibliothek mit Geschäftstabellen, die du diesen Agenten geben kannst, und eine Kundenoberfläche, in der die Menschen, für die das Projekt gedacht ist, mit ihnen sprechen.',
      '',
      'Hier gehört nichts zu einem bestimmten Geschäft. Es gibt keinen Katalog, keine Bestellungen, keine Produkttabelle. Was hier ist, ist die Maschinerie, die jedes solche Projekt braucht — ein neues Projekt beginnt deshalb bei „Was sollen die Agenten tun“ statt bei „Wie starte ich eine Agentenschleife“.',
      '',
      '## Was du bekommst',
      '',
      '| Baustein | Was es ist |',
      '| --- | --- |',
      '| Projekte | Bündeln Mitglieder, Agenten und die Speichertabellen, die sie nutzen dürfen, und halten den Arbeitsablauf, der entscheidet, wer eine Nachricht beantwortet |',
      '| Agenten | Ein Name, eine Beschreibung, die als System-Prompt dient, und die Fähigkeiten, die er trägt |',
      '| Fähigkeiten | Geschriebene Anweisungen plus die Werkzeuge, die sie brauchen |',
      '| Werkzeuge | Eine OpenAI-Funktionsspezifikation plus ein Python-Rumpf, beides in der Datenbank gespeichert |',
      '| Speicher | Tabellen, die du im Panel anlegst, mit Excel-Import und -Export |',
      '| Unterhaltungen | Ein WebSocket je Unterhaltung, der die Agentenschleife antreibt und Antworten streamt |',
      '| Gedächtnis | Notizen, die ein Agent über einen Benutzer schreibt, lesbar in dessen anderen Unterhaltungen |',
      '| Delegation | Ein Agent übergibt eine abgeschlossene Aufgabe an einen anderen Agenten im Projekt |',
      '| Benutzer und Rollen | `admin` baut die Projekte, `client` sieht nur die eigenen |',
      '| System-Projekt | Ein geschütztes Projekt mit einem Project-Manager-Agenten, der die Installation verwaltet |',
      '',
      '## Die Idee in einem Absatz',
      '',
      'Eine Nachricht trifft über das WebSocket der Unterhaltung ein. Die Agentenschleife liest den Arbeitsablauf des Projekts, wählt den Agenten oder die Gruppe, die antworten soll, baut den System-Prompt aus der Beschreibung des Agenten, seinen Fähigkeiten und der Ausgabe der vorab ausgeführten Werkzeuge und ruft das Modell auf. Werkzeugaufrufe kommen als Function Calls zurück; jeder wird gegen den in der Datenbank gespeicherten Werkzeugrumpf ausgeführt, wobei Projekt-, Unterhaltungs-, Agenten- und Benutzer-ID eingesetzt werden — ein Werkzeug kann also immer nur den eigenen Lauf berühren. Die Ergebnisse gehen zurück an das Modell, und der erzeugte Text wird in die Unterhaltung gesendet.',
      '',
      'Weil Werkzeug- und Fähigkeitsdefinitionen in der Datenbank statt im Code liegen, wirkt eine Änderung im Panel beim nächsten Lauf — ohne Neustart und ohne Deployment.',

      '',
      '## Author',
      '![Islomkhon Nizomkhonov](/IslomkhonNizomkhonov.png)',
      '',
      '### Islomkhon Nizomkhonov (小伊)',
      '',
      '- **Ausbildung**: Master in Informatik, China University of Mining and Technology',
      '- **Kernkompetenzen**: Software Engineering, Deep Learning, Machine Learning, Data Science, IoT, Predictive Maintenance',
      '',
      'Islomkhon Nizomkhonov wurde 1994 in Taschkent, Usbekistan, geboren. Er ist Senior Software Engineer mit mehr als sechs Jahren Erfahrung in Machine Learning und Predictive Maintenance. Er hat mit verschiedenen Branchen und großen Unternehmen gearbeitet, darunter [XCMG (徐工集团)](https://www.xcmg.com/) und [Uztelecom (der nationale Telekommunikationsanbieter Usbekistans)](https://uztelecom.uz/), und dort Lösungen auf Basis von Deep-Learning-Verfahren entwickelt. Seine Forschung befasst sich mit dem Einsatz neuronaler Netze zur Fehlerdiagnose in industriellen IoT-Systemen. Aktuell liegen seine Schwerpunkte auf **AI Agents**, **Software Engineering für und mit KI** und **vertrauenswürdiger KI**. Wenn Sie zusammenarbeiten oder einen Anwendungsfall besprechen möchten, erreichen Sie ihn per E-Mail unter [islomkhon@126.com](mailto:islomkhon@126.com) oder telefonisch unter +86 139 1487 4257.',
    ].join('\n'),
  },
  {
    id: 'quick-start',
    title: 'Schnellstart',
    body: [
      '## Voraussetzungen',
      '',
      '- Python 3.12+ und Node 20+',
      '- PostgreSQL, oder SQLite für einen schnellen Blick, wenn du `DATABASE_URL` auf dem Standardwert lässt',
      '',
      '## 1. Datenbank',
      '',
      '```bash',
      'docker compose up -d              # oder DATABASE_URL auf einen vorhandenen Server richten',
      'createdb cerebrumkit              # wenn du Postgres selbst betreibst',
      '```',
      '',
      '## 2. Backend',
      '',
      '```bash',
      'cd backend',
      'python -m venv venv',
      'venv/Scripts/python.exe -m pip install -r requirements.txt      # Windows',
      '# source venv/bin/activate && pip install -r requirements.txt   # macOS / Linux',
      'cp .env.example .env              # dann DATABASE_URL, SECRET_KEY,',
      '                                  # DEEPSEEK_* und die SEED_*-Konten setzen',
      'venv/Scripts/python.exe seed_all.py',
      '```',
      '',
      '`seed_all.py` legt die Tabellen, die Länderliste, die Admin- und Client-Konten, die allgemeinen Werkzeuge und Fähigkeiten sowie das System-Projekt mit seinem Project-Manager-Agenten an. Jeder Schritt ist idempotent, ein erneuter Lauf ist also ungefährlich.',
      '',
      'Es kopiert außerdem `DEEPSEEK_*` in die Tabelle `platforms` — darauf läuft das System tatsächlich. Danach ist **Einstellungen -> LLM-Verbindungen** die Stelle, an der Anbieter, Basis-URL, API-Schlüssel oder Modell geändert werden.',
      '',
      '## 3. Frontend',
      '',
      '```bash',
      'cd ../frontend/cerebrumkit-vue',
      'npm install',
      'npm run dev',
      '```',
      '',
      'Unter Windows kannst du auch `run.ps1` doppelklicken; das startet beide Server, `stop.ps1` stoppt sie.',
      '',
      '## 4. Anmelden',
      '',
      'Öffne <http://localhost:5173> und melde dich mit den `SEED_ADMIN_EMAIL` / `SEED_PASSWORD` an, die du in `backend/.env` gesetzt hast.',
      '',
      '> Ändere die Seed-Passwörter, bevor jemand anderes die Installation erreichen kann.',
      '',
      '## 5. Auf ein Modell zeigen',
      '',
      'Öffne **Einstellungen -> LLM-Verbindungen**. Die Verbindung, die der Seeder aus `.env` kopiert hat, ist bereits aktiv und als **In Verwendung** markiert. Drücke **Testen**: Das macht einen kleinen echten Aufruf, sodass eine falsche URL, ein falscher Schlüssel oder Modellname hier auffällt statt mitten in einem Lauf.',
      '',
      '## 6. Erste Unterhaltung',
      '',
      'Öffne **Projekte**, wähle das Projekt **System**, öffne eine Unterhaltung und frag den Project Manager etwas. Wenn er antwortet, funktioniert die Installation von Ende zu Ende.',
      '',
      'Um dein eigenes Ding zu bauen, folge **Ein Projekt aufbauen** unten. Oder bitte den Project Manager, es für dich zu tun — genau dafür gibt es das System-Projekt.',
    ].join('\n'),
  },
  {
    id: 'concepts',
    title: 'Grundbegriffe',
    body: [
      'Alles Weitere auf dieser Seite ist ein Detail zu einem dieser Begriffe.',
      '',
      '| Begriff | Was es ist |',
      '| --- | --- |',
      '| **Projekt** | Die Arbeitseinheit. Besitzt einen Arbeitsablauf, eine Menge Mitglieder, eine Menge Agenten und eine Menge Speichertabellen. |',
      '| **Agent** | Ein Name, eine Beschreibung, die zum System-Prompt wird, und die Fähigkeiten, die er trägt. Antwortet in Unterhaltungen der Projekte, zu denen er gehört. |',
      '| **Fähigkeit** | Ein geschriebener Anweisungsblock plus die Werkzeuge, die diese Anweisung braucht. Eine Fähigkeit an einen Agenten zu hängen gibt ihm diese Werkzeuge. |',
      '| **Werkzeug** | Eine Funktionsspezifikation (was das Modell sieht) plus ein Python-Rumpf (was tatsächlich läuft). Beides sind Zeilen in der Datenbank. |',
      '| **Kontext-Werkzeug** | Ein Werkzeug, das ein Agent läuft, *bevor* er die Nachricht liest; seine Ausgabe landet im System-Prompt. |',
      '| **Arbeitsablauf** | Der start/group/stop-Graph, der entscheidet, welche Agenten in welcher Reihenfolge antworten. |',
      '| **Speichertabelle** | Eine echte Datenbanktabelle, im Panel angelegt, mit Beschreibung an der Tabelle und an jeder Spalte. |',
      '| **Unterhaltung** | Ein Gespräch zwischen einem Benutzer und den Agenten eines Projekts, über ein WebSocket geführt. |',
      '| **Gedächtnis** | Eine Notiz, die ein Agent über einen Benutzer schreibt, mit Schlüssel (Agent, Benutzer) — lesbar in allen Unterhaltungen dieses Benutzers. |',
      '| **LLM-Verbindung** | Eine Zeile in `platforms`: Basis-URL, API-Schlüssel, Modell, Temperatur, Max. Tokens, Denken. Eine davon ist aktiv. |',
      '| **System-Projekt** | Das eine Projekt, das nicht umbenannt oder gelöscht werden kann. Beherbergt den Project Manager. |',
    ].join('\n'),
  },
  {
    id: 'run-lifecycle',
    title: 'Wie aus einer Nachricht eine Antwort wird',
    body: [
      'Das ist die ganze Schleife, in Reihenfolge. Jeder Schritt nennt die Datei, die ihn ausführt.',
      '',
      '1. **Der Benutzer sendet eine Nachricht** über das WebSocket der Unterhaltung (`backend/app/routers/websocket.py`). Das Token wird geprüft, und der Benutzer muss die Unterhaltung tatsächlich besitzen — ein gültiges Token allein genügt nicht. Die Nachricht geht als Hintergrundaufgabe an die Agentenschleife, ein Lauf blockiert also nie das Socket.',
      '2. **Die Schleife lädt den Arbeitsablauf des Projekts** (`backend/app/core/agent_loop.py`). Sie findet den `start`-Knoten und läuft den Graphen ab. Ein Lauf ist auf 200 Schritte begrenzt — ein Sicherheitsnetz gegen fehlerhafte oder zyklische Arbeitsabläufe.',
      '3. **Ein Gruppenknoten führt seine Agenten aus**, nacheinander, in der Reihenfolge der Zuordnung. Fehlende Agenten werden mit einer Warnung übersprungen, statt einen Aufruf für nichts zu verbrauchen.',
      '4. **Der Prompt jedes Agenten wird aus vier Dingen gebaut**: `You are {name}. {description}`, wobei die Beschreibung *der* stehende Auftrag des Agenten ist; die Ausgabe seiner **Kontext-Werkzeuge**, die jetzt laufen, jeweils unter eigener Überschrift (insgesamt höchstens 24.000 Zeichen); die **eigene letzte Antwort** des Agenten in dieser Unterhaltung, als vorheriger Turn eingesetzt, damit eine Rückfrage an frühere Arbeit anknüpft statt kalt neu zu beginnen (letzte 2.000 Zeichen); und die eingehende Nachricht.',
      '5. **Das Modell wird aufgerufen**, über die aktive LLM-Verbindung des Systems. Der Client wird wiederverwendet, solange die Konfiguration dahinter unverändert ist, denn ein Neubau wirft seinen HTTP-Verbindungspool weg.',
      '6. **Werkzeugaufrufe werden ausgeführt.** Jeder wird gegen Projekt, Unterhaltung, Agent und Werkzeug geprüft, dann wird der Rumpf kompiliert und aufgerufen, wobei `project_id`, `chat_id`, `agent_id`, `user_id` und `call_depth` bereits im Scope liegen (`backend/app/core/tool_exec.py`).',
      '7. **Ergebnisse gehen zurück ans Modell.** Ein Ergebnis über 8.000 Zeichen wird *innerhalb* seines JSON gekürzt statt abgeschnitten, weil ein halbes JSON-Objekt das Modell denselben Aufruf erneut senden lässt, statt zu antworten. Das vollständige Ergebnis bleibt auf der Werkzeugkarte in der Unterhaltung erhalten.',
      '8. **Die Antwort wird gespeichert und gesendet.** Werkzeugaufrufe erscheinen als eigene Karten im Verlauf, und der Text des Agenten streamt in das Gespräch.',
      '9. **Der nächste Knoten läuft** mit der kombinierten Ausgabe der vorherigen Gruppe als Eingabe. Die letzte Gruppe antwortet dem Benutzer.',
      '',
      'Ein Lauf kann vom Client aus mittendrin gestoppt werden; die Aufgabe wird abgebrochen und die Unterhaltung wird wieder inaktiv.',
      '',
      '## Was der Agent sieht und was nicht',
      '',
      '- Er bekommt **nicht** den früheren Gesprächsverlauf (`HISTORY_WINDOW` ist `0`).',
      '- Er bekommt **doch** seine eigene vorherige Antwort, alles, was seine Kontext-Werkzeuge holen, und alles, was Werkzeuge während des Laufs zurückgeben.',
      '- Für Erinnerung über Unterhaltungen hinweg gibt es das **Gedächtnis**: Ein Agent schreibt mit `memory_write` eine Notiz und liest sie mit `memory_lookup` in jeder späteren Unterhaltung mit demselben Benutzer zurück.',
      '',
      'Diese Form ist Absicht. Ein unbegrenzter Verlauf verdrängt die Werkzeuge und die aktuelle Anfrage, und meist braucht der Agent *einen Fakt, den er gelernt hat*, nicht den Wortlaut des Gesprächs.',
    ].join('\n'),
  },  {
    id: 'building-a-project',
    title: 'Ein Projekt aufbauen',
    body: [
      'Baue es entweder im Panel (**Projekte -> Projekt erstellen**) oder bitte den Project Manager in der Unterhaltung des System-Projekts, es für dich zu tun. Die Reihenfolge, die funktioniert:',
      '',
      '1. **Speicher** — lege die Tabellen an, die dem Projekt gehören, mit einer Beschreibung an der Tabelle und an jeder Spalte. Werkzeuge lesen sie, und der Agent sieht die Beschreibungen.',
      '2. **Werkzeuge** — eines je Sache, die ein Agent tun können soll. Schreib den Python-Rumpf, wenn du ihn kennst, oder beschreibe das Werkzeug und lass den Generator die Spezifikation entwerfen.',
      '3. **Fähigkeiten** — gruppiere die Werkzeuge unter geschriebenen Anweisungen: wann man sie benutzt, was man übergibt, wie man das Ergebnis liest.',
      '4. **Agenten** — eine Beschreibung, die der stehende Auftrag des Agenten ist, plus die Fähigkeiten, die er trägt. Optional Werkzeuge, die vor jeder Nachricht laufen.',
      '5. **Projekt** — weise die Tabellen zu, füge die Agenten hinzu und verdrahte den Arbeitsablauf, damit Nachrichten sie erreichen.',
      '6. **Benutzer** — lege Client-Konten an und füge sie dem Projekt hinzu. Sie sehen nur ihre eigenen Projekte und Unterhaltungen.',
      '',
      'Zwei Gewohnheiten, die sich auszahlen:',
      '',
      '- **Schreib die Beschreibungen, als wären sie für eine neue Kollegin.** Die Beschreibungen von Tabelle, Spalte, Werkzeug und Fähigkeit sind alles, was das Modell über deine Daten weiß. „Customer Lifetime Value in EUR, nächtlich aktualisiert“ ist zehn Zeilen Code wert; „eine Zahl“ ist nichts wert.',
      '- **Gib einem Agenten eine Aufgabe.** Ein Agent mit vier Fähigkeiten und zwanzig Werkzeugen ist in allen schlechter als vier Agenten mit je einer, weil jede Werkzeugbeschreibung um die Aufmerksamkeit des Modells konkurriert.',
    ].join('\n'),
  },
  {
    id: 'workflow',
    title: 'Der Arbeitsablauf',
    body: [
      'Der Arbeitsablauf ist ein kleiner Graph, der als JSON am Projekt gespeichert ist. Er hat drei Arten von Knoten:',
      '',
      '| Knoten | Was er tut |',
      '| --- | --- |',
      '| `start` | Wo eine Nachricht eintritt. Genau einer. |',
      '| `group` | Führt die ihm zugewiesenen Agenten nacheinander aus, in Reihenfolge. |',
      '| `stop` | Beendet diesen Pfad. |',
      '',
      '`wires` verbinden sie. Die kombinierte Ausgabe einer Gruppe geht an den folgenden Knoten, eine zweite Gruppe sieht also die Arbeit der ersten als ihre Eingabe. Die Ausgabe der **letzten** Gruppe ist die Antwort an den Benutzer.',
      '',
      '```json',
      '{',
      '  "nodes": [',
      '    { "id": 1, "type": "start", "label": "Start" },',
      '    { "id": 2, "type": "group", "label": "Default Group",',
      '      "agents": [ { "id": 1, "name": "Project Manager" } ] },',
      '    { "id": 3, "type": "stop", "label": "Stop" }',
      '  ],',
      '  "wires": [',
      '    { "id": "1-out->2-in", "fromNode": 1, "fromPort": "1-out", "toNode": 2, "toPort": "2-in" },',
      '    { "id": "2-out->3-in", "fromNode": 2, "fromPort": "2-out", "toNode": 3, "toPort": "3-in" }',
      '  ]',
      '}',
      '```',
      '',
      '## Agenten verketten',
      '',
      'Zwei hintereinander verdrahtete Gruppen sind der Bauplan einer Pipeline: ein Recherche-Agent, der sammelt, dann ein Schreib-Agent, der entwirft, dann ein Prüf-Agent, der kontrolliert. Jede Gruppe sieht, was die vorherige produziert hat.',
      '',
      'Halte Ketten kurz. Jede Gruppe ist ein voller Modell-Durchlauf mit eigenem Werkzeugbudget, eine fünfstufige Kette sind also fünf Chancen, den Faden zu verlieren, und fünffache Latenz.',
    ].join('\n'),
  },
  {
    id: 'agents',
    title: 'Agenten',
    body: [
      'Ein Agent ist ein Name, eine Beschreibung und eine Menge Fähigkeiten.',
      '',
      '**Die Beschreibung ist der System-Prompt.** Sie ist keine Dokumentation. Schreib sie als stehenden Auftrag: wer dieser Agent ist, wofür er verantwortlich ist, wie er sich verhalten soll, was er ablehnen soll. Die Schleife verpackt sie als `You are {name}. {description}` und hängt eine kurze Anweisung an, hilfreich, knapp und sparsam mit Werkzeugen zu sein.',
      '',
      '**Fähigkeiten bringen die Werkzeuge.** Ein Agent hat keine direkte Werkzeugliste; er hat Fähigkeiten, und jede Fähigkeit trägt Werkzeuge. Deshalb heißt eine neue Möglichkeit hinzuzufügen, eine Fähigkeit anzuhängen, statt zwölf Kästchen anzukreuzen.',
      '',
      '**Kontext-Werkzeuge** (optional) sind Werkzeuge, die der Agent von selbst läuft, bevor er die Nachricht liest. Nutze sie für das, was im Voraus bekannt und immer nötig ist — das aktuelle Datum, das Profil des Benutzers, ein Produktkatalog. Jedes Ergebnis landet im System-Prompt unter einer Überschrift, die du schreibst. Siehe **Kontext-Werkzeuge** unten.',
      '',
      '**Aktiv** ist nur ein Ausschalter: Ein inaktiver Agent wird übersprungen, und seine Fähigkeiten sind über ihn nicht nutzbar.',
      '',
      '## Eine gute Beschreibung',
      '',
      '```text',
      'Du bist der Support-Agent für einen Online-Shop. Du beantwortest Fragen zu',
      'Bestellungen, Lieferung und Rücksendungen. Suche Bestellungen mit order_lookup',
      '— frag den Kunden nie nach einer Bestellnummer, die du in seinem Konto findest.',
      'Wenn eine Erstattung verlangt wird, prüfe zuerst das Rückgabefenster, bevor du',
      'etwas versprichst. Geht es um ein Produkt, das du im Katalog nicht siehst, sag',
      'das und biete an, es an eine Kollegin weiterzugeben.',
      '```',
      '',
      'Beachte, was sie tut: Sie nennt die Werkzeuge, benennt die Grenzen und sagt, was bei Stocken zu tun ist. Die Beschreibung „hilfreicher Support-Agent“ erzeugt einen hilfreichen Agenten, der Bestellnummern erfindet.',
    ].join('\n'),
  },
  {
    id: 'skills',
    title: 'Fähigkeiten',
    body: [
      'Eine Fähigkeit ist eine geschriebene Anweisung plus die Werkzeuge, die diese Anweisung braucht. Gib dem Agenten die Fähigkeit, und die Werkzeuge kommen mit.',
      '',
      'Der Fähigkeitstext ist Markdown und landet im System-Prompt des Agenten. Er ist der Ort für das prozedurale Wissen, das nicht in die Agentenbeschreibung passt:',
      '',
      '- **Wann diese Fähigkeit zu nutzen ist** — der Auslöser, damit der Agent sie im richtigen Moment wählt.',
      '- **Anweisungen** — die Schritte, in Reihenfolge.',
      '- **Beispiele** — ein Aufruf und die Form eines guten Ergebnisses.',
      '- **Hinweise und Fallstricke** — der Fehler, den der Agent sonst jedes Mal machen würde.',
      '',
      'Die mitgelieferten Fähigkeiten sind gute Vorlagen. **„System Administration“** bündelt die `manage_*`-Werkzeuge mit den Regeln für ihre Nutzung; **„Delegate a Self-Contained Task to Another Agent“** ist ein vollständig ausgearbeitetes Beispiel des Formats.',
      '',
      'Fähigkeiten sind über Agenten und Projekte hinweg wiederverwendbar. Wenn zwei Agenten dieselbe Prozedur brauchen, schreib sie einmal.',
    ].join('\n'),
  },
  {
    id: 'tools',
    title: 'Werkzeuge',
    body: [
      'Ein Werkzeug hat zwei Hälften, beide auf der Werkzeugzeile gespeichert:',
      '',
      '| Feld | Was es enthält |',
      '| --- | --- |',
      '| `description` | Die OpenAI-Funktionsspezifikation als JSON — der Name, die Beschreibung, die das Modell liest, und die Parameter |',
      '| `body` | Das Python, das läuft, und eine Funktion mit demselben Namen wie die Spezifikation definiert |',
      '',
      'Der Knopf **Generieren** im Panel entwirft beides aus einer Beschreibung in normaler Sprache, mit dem in den Einstellungen konfigurierten Modell. Prüfe, was er schreibt — besonders einen Rumpf, siehe den Sicherheitshinweis unten.',
      '',
      '## Die Funktionsspezifikation',
      '',
      '```json',
      '{',
      '  "type": "function",',
      '  "function": {',
      '    "name": "order_lookup",',
      '    "description": "Look up one order by its id. Returns status, items and delivery date.",',
      '    "parameters": {',
      '      "type": "object",',
      '      "properties": {',
      '        "order_id": { "type": "integer", "description": "The order id." }',
      '      },',
      '      "required": ["order_id"]',
      '    }',
      '  }',
      '}',
      '```',
      '',
      'Schreib die Beschreibung für das Modell, nicht für einen Menschen: Sag, was das Werkzeug zurückgibt, und sag, was es *nicht* tut, damit das Modell nicht versehentlich danach greift.',
      '',
      '## Der Rumpf',
      '',
      'Der Rumpf definiert eine Funktion, deren Name zu `function.name` passen muss. Sie läuft, wenn die IDs des Laufs bereits im Scope sind:',
      '',
      '| Variable | Was sie ist |',
      '| --- | --- |',
      '| `project_id` | Das Projekt, zu dem der Lauf gehört |',
      '| `chat_id` | Die Unterhaltung, zu der der Lauf gehört |',
      '| `agent_id` | Der Agent, der das Werkzeug aufgerufen hat |',
      '| `user_id` | Der **Eigentümer der Unterhaltung** — nicht, wer getippt hat, denn ein Admin kann in die Unterhaltung eines anderen schreiben |',
      '| `call_depth` | `0` für einen von einem Menschen gestarteten Lauf, `1` für einen delegierten, und so weiter |',
      '',
      'Diese liefert der Server, und sie dürfen nie als Parameter deklariert werden — ein Modell, das `project_id` übergeben könnte, könnte jedes Projekt lesen.',
      '',
      '```python',
      'def order_lookup(order_id: int):',
      '    from app.core.database import SessionLocal',
      '    from sqlalchemy import text',
      '',
      '    db = SessionLocal()',
      '    try:',
      '        row = db.execute(',
      '            text("SELECT id, status, delivered_at FROM orders "',
      '                 "WHERE id = :oid AND project_id = :pid"),',
      '            {"oid": order_id, "pid": project_id},',
      '        ).mappings().first()',
      '        if row is None:',
      '            return f"No order {order_id} in this project."',
      '        return dict(row)',
      '    finally:',
      '        db.close()',
      '```',
      '',
      'Zwei Regeln, die Werkzeuge verlässlich machen:',
      '',
      '- **Gib einen Satz zurück, keine Ausnahme.** Ein geworfener Fehler wird zu einem String, den das Modell liest; fängst du ihn, kannst du sagen, *warum* es fehlschlug.',
      '- **Beschränke jede Abfrage auf den Lauf.** Filtere nach `project_id` (und dem Benutzer), damit ein Werkzeug nur Daten berühren kann, die es bekommen hat.',
      '',
      '> **Sicherheit.** Ein Werkzeugrumpf ist beliebiges Python, kompiliert und mit vollen Builtins ausgeführt. Er ist bewusst nicht in einer Sandbox, weil die mitgelieferten Werkzeuge `requests`, SQLAlchemy und App-Interna importieren. Die Folge: Ein Werkzeug zu schreiben ist gleichbedeutend damit, Code auf dem Server auszuführen. Halte die Admin-Endpunkte für Werkzeuge admin-only und prüfe einen generierten Rumpf so, wie du Quellcode prüfen würdest.',
    ].join('\n'),
  },
  {
    id: 'context-tools',
    title: 'Kontext-Werkzeuge',
    body: [
      'Manches, was ein Agent braucht, ist vor dem Lesen der Nachricht bekannt: die Umgebung, in der er läuft, das Profil des Benutzers, der Katalog, mit dem er arbeitet. Solche Abfragen hängen nicht vom Wortlaut der Nachricht ab, sie dem Modell zu überlassen kostet also eine Werkzeugrunde und wird übersprungen, wann immer das Modell findet, es wisse schon genug.',
      '',
      'Ein **Kontext-Werkzeug** macht diese Abfrage zu einem Teil davon, wie der Agent startet. Das Werkzeug läuft, und seine Ausgabe landet im System-Prompt des Agenten unter der Überschrift, die du schreibst.',
      '',
      'Wählbar ist nur ein Werkzeug, das der Agent — über eine Fähigkeit — bereits hat. Für jedes legst du fest:',
      '',
      '| Einstellung | Bedeutung |',
      '| --- | --- |',
      '| Kommentar | Die Überschrift über der Ausgabe, damit der Agent weiß, worauf er blickt |',
      '| Argumente | Ein JSON-Objekt mit Argumenten für ein Werkzeug, das welche braucht; leer für eines ohne |',
      '| Reihenfolge | Was im Prompt zuerst erscheint |',
      '',
      'Der ganze Block ist auf 24.000 Zeichen begrenzt. Ein Eintrag, der nicht mehr passt, wird verworfen und gezählt statt halbiert, weil ein halbes JSON-Objekt das Modell einlädt, das Werkzeug erneut aufzurufen, um die Lücke zu füllen.',
      '',
      'Setze Kontext-Werkzeuge sparsam ein. Sie laufen bei **jeder** Nachricht, ein langsames addiert seine Latenz zu jedem Turn, und ein großes konkurriert mit der eigentlichen Anfrage um die Aufmerksamkeit des Modells.',
    ].join('\n'),
  },  {
    id: 'storage',
    title: 'Speicher',
    body: [
      'Der Speicher ist eine Bibliothek von Geschäftstabellen, die du im Panel anlegst, ohne eine Migration zu schreiben. Jede Tabelle ist eine echte Tabelle in der Datenbank.',
      '',
      'Eine Tabelle trägt:',
      '',
      '- Einen **Namen** und eine **Beschreibung**, die der Agent lesen kann.',
      '- **Spalten**, jede mit einem Typ und einer Beschreibung.',
      '- Eine Menge von **Projekten**, denen sie zugewiesen ist. Ein Werkzeug erreicht nur eine Tabelle, die seinem Projekt gehört.',
      '',
      'Spalten werden im Panel hinzugefügt und geändert, die zugrunde liegende Tabelle wird entsprechend mitgeändert. Zeilen lassen sich von Hand bearbeiten, und eine Tabelle kann **aus Excel importiert** und **nach Excel exportiert** werden — der Import zeigt die ersten Zeilen als Vorschau, damit du die Zuordnung vor dem Übernehmen siehst.',
      '',
      '## Warum die Beschreibungen zählen',
      '',
      'Der Agent sieht dein Schema nie. Er sieht die Tabellenbeschreibung und die Spaltenbeschreibungen und entscheidet daraus, ob und wie er abfragt. Eine Tabelle `t1` mit einer Spalte `val` ist für ihn unsichtbar. `customer_orders` mit `delivered_at — wann das Paket den Kunden erreicht hat; NULL während des Transports` ist brauchbar.',
      '',
      '## Wo es hingehört',
      '',
      'Gib einem Projekt seine Tabellen und schreib dann Werkzeuge, die sie lesen und schreiben. Das ist die übliche Form eines echten Projekts: Die Geschäftsdaten liegen im Speicher, und die Werkzeuge sind die Verben, die der Agent darauf ausführen darf.',
      '',
      'Tabellen, die außerhalb des Panels entstehen (indem du ein SQLAlchemy-Modell hinzufügst und `migrate.py` ausführst), können ebenfalls vom Speicher-Bildschirm einem Projekt zugewiesen werden.',
    ].join('\n'),
  },
  {
    id: 'memory',
    title: 'Gedächtnis',
    body: [
      'Das Gedächtnis ist, wie ein Agent sich zwischen Unterhaltungen an eine Tatsache über eine Person erinnert.',
      '',
      'Eine Notiz hat den Schlüssel **(Agent, Benutzer)**, nicht die Unterhaltung. Eine Notiz, die der Support-Agent am Montag schreibt, ist für denselben Agenten am Freitag lesbar — und für einen anderen Agenten nicht; das ist wichtig, weil Agenten verschiedene Aufgaben und verschiedenes Erinnerungswertes haben.',
      '',
      'Zwei Werkzeuge erledigen die Arbeit:',
      '',
      '| Werkzeug | Was es tut |',
      '| --- | --- |',
      '| `memory_write` | Eine Notiz über den aktuellen Benutzer speichern oder aktualisieren |',
      '| `memory_lookup` | Zurücklesen, was über den aktuellen Benutzer bekannt ist |',
      '',
      'Beide kommen mit der mitgelieferten Fähigkeit **„Context & Memory Awareness“**. Hänge sie an jeden Agenten, der Wissen weitertragen soll.',
      '',
      'Das Gedächtnis ist kein Verlauf. Es ist für dauerhafte Fakten — eine Vorliebe, eine Einschränkung, ein offener Punkt — und der Agent entscheidet, was es wert ist, behalten zu werden. Für das Gespräch selbst hat der Agent seine eigene letzte Antwort; für alles andere fragt er ab.',
    ].join('\n'),
  },
  {
    id: 'delegation',
    title: 'Delegation',
    body: [
      'Ein Agent kann eine abgeschlossene Aufgabe an einen anderen Agenten im selben Projekt übergeben und die Antwort nutzen.',
      '',
      'Das Werkzeug heißt `call_agent` und kommt in der mitgelieferten Fähigkeit **„Delegate a Self-Contained Task to Another Agent“** — die zugleich die beste Dokumentation des Musters ist, lies sie also im Bildschirm für Fähigkeiten.',
      '',
      'Die wichtige Eigenschaft: **Der andere Agent sieht nichts von deinem Gespräch.** Nicht die Nachricht des Benutzers, nicht deine Werkzeuge, nicht das, was du gefunden hast. Die `message`, die du übergibst, muss deshalb die ganze Anfrage tragen — Hintergrund, Ergebnis, Einschränkungen, erwartetes Format.',
      '',
      'Leitplanken, die das im Zaum halten:',
      '',
      '- Delegation geht höchstens **3 Agenten tief**. Zwei Agenten, die sich gegenseitig aufrufen, halten an, statt endlos zu schleifen.',
      '- Ein delegierter Lauf bekommt ein kleineres Werkzeugbudget (**8 Runden**) als ein von einem Menschen gestarteter, weil er innerhalb des Turns seines Aufrufers antworten muss.',
      '- Ein delegierter Lauf, der nicht rechtzeitig fertig wird, gibt einen erklärenden Satz zurück, den der Aufrufer wie jedes andere Werkzeugergebnis liest.',
      '',
      'Delegation ist kein Privileg — sie gehört nicht zur Systemadministration. Jeder Agent in einem Projekt kann sinnvoll Arbeit an einen anderen übergeben, gib die Fähigkeit also, wer sie braucht.',
    ].join('\n'),
  },
  {
    id: 'chats',
    title: 'Unterhaltungen und die Kundenoberfläche',
    body: [
      'Eine Unterhaltung gehört zu einem Benutzer und einem Projekt. Ihr WebSocket treibt die Schleife: Der Client sendet eine Nachricht, und der Server streamt Status, Tippanzeigen, Werkzeugkarten und Antworten zurück.',
      '',
      'Im Verlauf siehst du:',
      '',
      '- Die **Nachricht des Benutzers**, einmal.',
      '- Eine **Werkzeugkarte** je Werkzeugaufruf, mit Eingabe und Ausgabe — so lässt sich eine falsche Antwort bis zu dem Aufruf zurückverfolgen, der sie erzeugt hat.',
      '- **Flussnachrichten**: Wenn die Ausgabe eines Agenten zur Eingabe eines anderen wird, wird auch diese Übergabe festgehalten. Sie sind als Fluss markiert und nicht so dargestellt, als hätte ein Mensch sie getippt.',
      '- Die **Antwort des Agenten**.',
      '',
      'Ein Lauf kann mittendrin **gestoppt** werden; die Unterhaltung wird wieder inaktiv, und die bereits gespeicherte Teilarbeit bleibt im Verlauf.',
      '',
      '## Die Kundenoberfläche',
      '',
      'Clients sehen **ihre eigenen Projekte und Unterhaltungen, und nichts anderes**. Sie sehen die Werkzeuge, Fähigkeiten, den Arbeitsablauf oder die Speichertabellen hinter dem, was sie benutzen, nicht — nur das Gespräch. Genau diese Trennung ist der Punkt: Ein Betreiber kann den ganzen Agenten-Stack darunter neu bauen, ohne dass die Nutzer etwas anderes merken als bessere Antworten.',
    ].join('\n'),
  },
  {
    id: 'users-and-access',
    title: 'Benutzer, Rollen und Zugriff',
    body: [
      'Es gibt zwei Rollen.',
      '',
      '| Rolle | Darf |',
      '| --- | --- |',
      '| `admin` | Alles: Projekte, Agenten, Fähigkeiten, Werkzeuge, Speicher, Benutzer, LLM-Verbindungen. Sieht jede Unterhaltung. |',
      '| `client` | Die eigenen Projekte und die eigenen Unterhaltungen. Sonst nichts. |',
      '',
      'Benutzer werden unter **Benutzer** angelegt (oder vom Project Manager im Chat). Ein Client erreicht nur ein Projekt, dem er hinzugefügt wurde.',
      '',
      'Zugriffsregeln, die man kennen sollte:',
      '',
      '- **Öffentliche Selbstregistrierung erzeugt immer einen Client.** Die Rolle kommt vom Server, nie aus dem Request-Body — sonst könnte sich jeder ein Admin-Konto ausstellen.',
      '- **Erhöhte Rollen werden nur über die Admin-Endpunkte vergeben.**',
      '- **Eine Unterhaltung gehört ihrem Eigentümer.** Ein Nicht-Admin kann nicht in die Unterhaltung eines anderen schreiben, sie abonnieren oder ihren Lauf abbrechen.',
      '- **Anonyme Anfragen bekommen 401, falsche Rolle 403.** Jeder Admin-Router ist auf Router-Ebene geschützt, kein einzelner Endpunkt kann die Prüfung also vergessen.',
      '- **Anmeldung und Registrierung sind rate-limitiert.**',
      '',
      '> Ein Administrator *kann* in die Unterhaltung eines Clients schreiben. Der Lauf handelt dann trotzdem für den Eigentümer der Unterhaltung: `user_id` in einem Werkzeug ist der Eigentümer, nicht der Admin, der getippt hat.',
    ].join('\n'),
  },
  {
    id: 'llm-connections',
    title: 'LLM-Verbindungen',
    body: [
      'Das Modell, auf dem das ganze System läuft, ist eine Zeile in der Tabelle `platforms`, kein Wert in einer Konfigurationsdatei. Damit ist der Wechsel von Anbieter, Basis-URL, Schlüssel oder Modell eine Datenänderung, die ein Admin im Panel machen kann, statt eines Deployments.',
      '',
      '**Einstellungen -> LLM-Verbindungen** verwaltet sie. Jede Zeile enthält:',
      '',
      '| Feld | Bedeutung |',
      '| --- | --- |',
      '| Name | Eine Bezeichnung, um zwei Zeilen auseinanderzuhalten |',
      '| Basis-URL | Der API-Endpunkt (leer nutzt den Standard des Anbieters) |',
      '| API-Schlüssel | Das Credential, so gespeichert und angezeigt, wie eingegeben |',
      '| Modell | Der Modellname, der angefragt wird |',
      '| Temperatur | `0`–`2`; leer überlässt es dem Anbieter |',
      '| Max. Tokens | Obergrenze der Antwort; leer heißt kein Limit |',
      '| Denken | Ein Reasoning-Modell bitten, vor der Antwort nachzudenken |',
      '',
      '## Wie eine ausgewählt wird',
      '',
      '1. Die als **aktiv** markierte Zeile wird benutzt.',
      '2. Ist keine aktiv, wird die **erste** Zeile benutzt.',
      '3. Ist die Tabelle leer, gelten die `DEEPSEEK_*`-Werte aus `.env` — so steht eine frisch installierte Instanz da, bevor etwas gespeichert wurde.',
      '',
      'Genau eine Zeile ist gleichzeitig aktiv: Eine zu aktivieren nimmt den anderen die Markierung. Das Banner oben auf der Seite zeigt immer, welche Verbindung tatsächlich wirkt, du musst die Fallback-Regel also nie selbst anwenden.',
      '',
      '## Testen',
      '',
      '**Testen** macht einen kleinen echten Aufruf gegen diese Zeile und meldet, was zurückkam. Das ist der schnellste Weg, einen Schlüssel, eine URL oder einen Modellnamen zu prüfen — und es lohnt sich nach jeder Änderung, weil eine schlechte Verbindung sonst viel später als fehlgeschlagener Lauf auftaucht.',
      '',
      'Eine gespeicherte Änderung wirkt beim **nächsten Lauf**, ohne Neustart. Clients werden wiederverwendet, solange die Konfiguration dahinter unverändert ist, ein Anbieterwechsel wirft Verbindungspools also nicht ohne Grund weg.',
      '',
      '> Der API-Schlüssel wird so gespeichert und so zurückgegeben, wie er eingegeben wurde — er wird nicht maskiert. Der Einstellungs-Bildschirm ist genau deshalb admin-only: Wer die Liste lesen kann, kann gegen das Konto dahinter Geld ausgeben.',
    ].join('\n'),
  },  {
    id: 'system-project',
    title: 'Das System-Projekt und der Project Manager',
    body: [
      'Ein Projekt ist besonders. Es ist als `is_system` markiert, das heißt, seine eigene Zeile kann nicht umbenannt oder gelöscht werden — der Agent, der darin lebt, hat also immer ein Zuhause. Alles *innerhalb* bleibt editierbar, und genau das lässt die Konstruktion funktionieren.',
      '',
      'Es beherbergt den Agenten **Project Manager**, der die Fähigkeit **„System Administration“** und die Delegationsfähigkeit trägt. Seine Werkzeuge sind:',
      '',
      '| Werkzeug | Was es verwaltet |',
      '| --- | --- |',
      '| `manage_users` | Benutzer auflisten, lesen, anlegen, ändern, aktivieren oder deaktivieren |',
      '| `manage_projects` | Projekte, ihre Mitglieder, ihre Agenten und ihren Arbeitsablauf |',
      '| `manage_agents` | Agenten und die Fähigkeiten, die sie tragen |',
      '| `manage_skills` | Fähigkeiten und die Werkzeuge, die sie tragen |',
      '| `manage_tools` | Werkzeuge, inklusive Generierung von Spezifikation und Rumpf aus einer Beschreibung |',
      '| `manage_storage` | Speichertabellen, ihre Spalten und ihre Zeilen |',
      '| `call_agent` | Eine Aufgabe an einen anderen Agenten im Projekt übergeben |',
      '',
      'Die Installation lässt sich also administrieren, indem man **im Chat danach fragt**. Einen Benutzer anlegen, ein Projekt aufsetzen, ein Werkzeug schreiben, einen Arbeitsablauf verdrahten — der Project Manager erledigt das über dieselbe Service-Schicht, die das Panel nutzt, nicht über die REST-API.',
      '',
      'Es ist zugleich der schnellste Weg, das System kennenzulernen: Frag, was existiert, und beobachte, welche Werkzeugaufrufe zurückkommen.',
      '',
      'Leitplanken, die man kennen sollte: Der Project Manager kann das System-Projekt nicht löschen, sich nicht daraus entfernen und sich sein eigenes Heimatprojekt oder seine Fähigkeiten nicht nehmen — man kann sich also nicht versehentlich aus der Administration aussperren.',
    ].join('\n'),
  },
  {
    id: 'use-cases',
    title: 'Anwendungsfälle',
    body: [
      'CerebrumKit ist ein Ausgangspunkt, das hier sind also Formen statt fertiger Produkte. Jeder Fall ist dieselbe Maschinerie mit einer anderen Speicherbibliothek und einem anderen Werkzeugsatz.',
      '',
      '## 1. Ein Support-Schreibtisch, der aus deinen eigenen Daten antwortet',
      '',
      'Im **Speicher** liegen `customers`, `orders` und `articles`. **Werkzeuge** suchen eine Bestellung per id, finden einen Kunden per E-Mail und durchsuchen die Hilfeartikel. Ein Support-Agent trägt eine Fähigkeit, die ihm sagt: Identifiziere zuerst den Kunden, nenne nie ein Lieferdatum, das du nicht aus der Bestellung gelesen hast, und gib alles zu einer Erstattung an einen Menschen weiter.',
      '',
      'Die Kundenoberfläche ist dein Support-Postfach. Wertvoll sind die Werkzeugbeschreibungen und der Fähigkeitstext, nicht das Modell: ein gewöhnliches Modell plus deine Bestelltabelle schlägt ein großartiges Modell ohne Daten.',
      '',
      '## 2. Eine Betriebskonsole über einem Geschäftssystem',
      '',
      'Deine echten Daten liegen in einem anderen System hinter einer HTTP-API. Das mitgelieferte Werkzeug **`api_call`** stellt Anfragen; schreib dünne Werkzeuge je Endpunkt — `get_invoice`, `list_open_tickets`, `approve_leave` —, damit der Agent mit benannten Verben arbeitet statt mit rohen URLs.',
      '',
      'Zwei Agenten im Arbeitsablauf verkettet: einer sammelt und fasst zusammen, einer entwirft die Aktion. Ein Mensch liest den Entwurf im Chat, bevor etwas freigegeben wird. Erst Nur-Lese-Werkzeuge; die Schreibpfade kommen dazu, sobald du den Beschreibungen traust.',
      '',
      '## 3. Inside Sales: Recherche vor dem Anruf',
      '',
      'Ein Recherche-Agent mit einer `web_search`-Fähigkeit und einem `company_lookup`-Werkzeug über einer `accounts`-Tabelle. Sein **Kontext-Werkzeug** lädt den Kundendatensatz vor jeder Nachricht vor, sodass „Womit soll ich einsteigen?“ gegen echte Daten beantwortet wird, statt zurückgefragt zu werden.',
      '',
      'Delegation zahlt sich hier aus: Der Hauptagent übergibt „Fasse die letzten beiden Quartale zusammen“ an einen Recherche-Agenten und nutzt die Antwort, ohne dass der Recherche-Agent den ganzen Verlauf sieht.',
      '',
      '## 4. Dokumenteneingang im Backoffice',
      '',
      'Bearbeiter fügen extrahierten Dokumenttext in einen Chat ein oder laden ihn hoch. Werkzeuge gleichen ihn mit Referenztabellen im Speicher ab und schlagen Buchungen vor. Eine Freigabeschlange ist einfach ein zweites Projekt, dessen Agent schreiben darf.',
      '',
      'Der Excel-Import einer Speichertabelle ist der Weg, auf dem die Referenzdaten hineinkommen; der Export ist der Weg, auf dem eine Prüferin das Ergebnis mitnimmt.',
      '',
      '## 5. Ein produktisierter Assistent für deine eigenen Kunden',
      '',
      'Ein Projekt je Kunde, jedes mit eigenen Speichertabellen und eigenen Agenten, und Client-Konten, die auf ihr Projekt beschränkt sind. Das Admin-Panel ist dein Backoffice; die Kundenoberfläche ist das Produkt.',
      '',
      'Weil ein Client nur seine eigenen Unterhaltungen sieht und nie die Werkzeuge oder Tabellen dahinter, kannst du die Fähigkeiten eines Agenten zwischen Sitzungen neu bauen, ohne dass der Kunde etwas anderes merkt, als dass sich die Antworten ändern.',
      '',
      '## 6. Die Plattform administrieren, indem man mit ihr spricht',
      '',
      'Auch ganz ohne Geschäftsdomäne ist das System-Projekt nützlich: Bitte den Project Manager, einen Benutzer anzulegen, ein Projekt aufzusetzen, aus einer Beschreibung ein Werkzeug zu schreiben, es an eine Fähigkeit zu hängen und in einen Arbeitsablauf einzubauen. Lies dann die Werkzeugkarten im Verlauf und sieh genau, was er getan hat.',
      '',
      'Für alle, die das System lernen, ist das die schnellstmögliche Tour — und ein funktionierendes Beispiel des ganzen Entwurfs.',
    ].join('\n'),
  },
  {
    id: 'security',
    title: 'Sicherheit und Vertrauen',
    body: [
      'Das Vertrauensmodell sollte man klar aussprechen, weil zwei seiner Eigenschaften Absicht sind und eine davon scharf ist.',
      '',
      '## Ein Werkzeugrumpf ist Codeausführung',
      '',
      'Werkzeugrümpfe werden kompiliert und mit vollen Builtins ausgeführt. Sie sind **nicht in einer Sandbox**, weil die mitgelieferten Werkzeuge `requests`, SQLAlchemy und App-Interna importieren und eines vom Modell verfassten SQL an die Datenbank übergibt — eine Sandbox mit eingeschränkten Builtins würde sie alle brechen.',
      '',
      'Also: Ein Werkzeug zu schreiben ist gleichbedeutend damit, Code auf dem Server auszuführen. Die Admin-Endpunkte für Werkzeuge müssen admin-only bleiben, und `tools.body` sollte geprüft werden, wie du einen Commit prüfen würdest. Deshalb entwirft der Knopf **Generieren** zwar einen Rumpf, installiert ihn aber nicht stillschweigend.',
      '',
      'Ein Aufrufer erreicht trotzdem kein Werkzeug, das nicht an seinen Agenten gehängt ist, und einem Werkzeugrumpf kann das Modell kein `project_id` übergeben — der Server liefert die IDs des Laufs selbst.',
      '',
      '## Zugriffskontrolle',
      '',
      '| Regel | Wo sie durchgesetzt wird |',
      '| --- | --- |',
      '| Admin-Router sind admin-only | Abhängigkeit auf Router-Ebene, kein Endpunkt kann sie vergessen |',
      '| Registrierung kann keinen Admin erzeugen | Die Rolle wird serverseitig gesetzt, nie aus dem Body gelesen |',
      '| Eine Unterhaltung gehört ihrem Eigentümer | Auf den REST-Routen geprüft und erneut am WebSocket |',
      '| Der Verlauf ist nicht über Benutzer hinweg lesbar | Nicht-Admins werden immer auf ihre eigenen Zeilen gefiltert |',
      '| Anmeldung und Registrierung sind rate-limitiert | Sliding-Window-Limiter je Client |',
      '',
      '## Credentials',
      '',
      '- LLM-API-Schlüssel liegen in der Datenbank und werden in den Einstellungen **unmaskiert** angezeigt; dieser Bildschirm ist bewusst admin-only.',
      '- `SECRET_KEY` signiert die JWTs. Beim Start warnt die App, wenn er noch auf dem Beispielwert steht — ändere ihn, bevor jemand anderes die Installation erreicht.',
      '- Die Seed-Konten haben Seed-Passwörter. Ändere sie.',
      '- `.env` wird nicht eingecheckt. Lass es so.',
      '',
      '## Wo Modellausgabe als nicht vertrauenswürdig gilt',
      '',
      '- Der Tabellenexport neutralisiert Formelinjektion, eine Zelle, die mit `=` beginnt, kann in Excel also nicht ausgeführt werden.',
      '- Werkzeugergebnisse werden gekürzt, bevor sie das Modell erreichen, und innerhalb ihres JSON beschnitten statt abgeschnitten.',
      '- Arbeitsabläufe sind in Schritten, Werkzeugrunden, Delegationstiefe und Werkzeugdauer begrenzt, kein einzelner Lauf kann also ewig drehen.',
    ].join('\n'),
  },
  {
    id: 'operations',
    title: 'Betrieb',
    body: [
      '## Starten',
      '',
      '```bash',
      '# Backend',
      'cd backend && venv/Scripts/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8000',
      '',
      '# Frontend',
      'cd frontend/cerebrumkit-vue && npm run dev',
      '```',
      '',
      'Unter Windows startet `run.ps1` beide, `stop.ps1` stoppt sie. Für die Produktion behandelt `DEPLOY.md` nginx, systemd und einen Rebuild-Weg, der die Datenbankzeilen (Werkzeuge, Fähigkeiten, Agenten) mit dem Code im Gleichschritt hält.',
      '',
      '## Datenbankänderungen',
      '',
      '`backend/migrate.py` legt fehlende Tabellen an und ergänzt fehlende Spalten. Ein erneuter Lauf ist sicher: So wird eine neue Installation hochgebracht, und so wird ein neues Modell in `backend/app/models/` zu einer Tabelle.',
      '',
      '## Seeding',
      '',
      '| Skript | Was es tut |',
      '| --- | --- |',
      '| `seed_all.py` | Alles Folgende, in Reihenfolge — der eine Befehl, den eine frische Installation braucht |',
      '| `seed.py` | Admin- und Client-Konten aus den `SEED_*`-Variablen |',
      '| `seed_countries.py` | Die Länderliste |',
      '| `seed_general_tools.py` | Die allgemeinen Werkzeuge und ihre Fähigkeiten |',
      '| `seed_system_project.py` | Das System-Projekt und den Project Manager |',
      '',
      'Alle sind idempotent — Zeilen werden über den Namen gefunden und an Ort und Stelle aktualisiert —, ein erneuter Lauf nach einer Änderung am Werkzeugrumpf schiebt die Korrektur also durch.',
      '',
      '## Daten zwischen Installationen bewegen',
      '',
      '`export_for_deploy.py` schreibt die Projektdaten heraus, `load_for_deploy.py` liest sie ein. Nutze sie, um Werkzeuge, Fähigkeiten, Agenten und Speicherdefinitionen von einer Entwicklungsinstallation in eine deployte Instanz zu bringen.',
      '',
      '## Logs',
      '',
      'Der Helfer `run.ps1` schreibt `backend.log` / `backend.err.log` und `frontend.log` / `frontend.err.log` neben das Projektverzeichnis. Ein fehlgeschlagener Lauf wird mit der Unterhaltungs-ID protokolliert, eine Meldung „er hat nicht geantwortet“ lässt sich also bis zu dem Lauf zurückverfolgen, der fehlschlug.',
      '',
      '## Eine Agentenänderung deployen',
      '',
      'Die meisten Agentenänderungen brauchen gar kein Deployment: Bearbeite Werkzeug, Fähigkeit oder Agenten im Panel, es wirkt beim nächsten Lauf. Neu deployen musst du nur, wenn sich der **Code** ändert — die Agentenschleife, ein Router, ein Modell.',
    ].join('\n'),
  },
  {
    id: 'reference',
    title: 'Referenz',
    body: [
      '## Grenzen',
      '',
      'Jede Obergrenze existiert, damit ein außer Kontrolle geratener Lauf nicht das System frisst. Sie stehen in `backend/app/core/agent_loop.py`.',
      '',
      '| Grenze | Wert | Warum |',
      '| --- | --- | --- |',
      '| Werkzeugrunden je Agenten-Turn | 100 | Hält ein Modell davon ab, in Werkzeugaufrufen zu schleifen |',
      '| Werkzeugrunden in einem delegierten Lauf | 8 | Er muss innerhalb des Turns seines Aufrufers antworten |',
      '| Delegationstiefe | 3 | Zwei Agenten, die sich gegenseitig aufrufen, halten an |',
      '| Timeout je Werkzeugaufruf | 60 s | Ein Werkzeug, das nie zurückkehrt, kann den Lauf nicht aufhängen |',
      '| Timeout je Delegationsaufruf | 300 s | Ein verschachtelter Lauf braucht länger als ein normales Werkzeug |',
      '| Werkzeugergebnis ans Modell | 8.000 Zeichen | Eine große API-Antwort kann das Kontextfenster nicht auffressen |',
      '| Werkzeugkarte im Chat | 100.000 Zeichen | Die Karte ist für einen Menschen und trotzdem begrenzt |',
      '| Kontext-Werkzeuge vorab, gesamt | 24.000 Zeichen | Hält den System-Prompt im Verhältnis |',
      '| Eigene letzte Antwort des Agenten | 2.000 Zeichen | Genug für das Fazit, nicht für eine ganze Seite JSON |',
      '| Arbeitsschritte je Lauf | 200 | Sicherheitsnetz für fehlerhafte oder zyklische Arbeitsabläufe |',
      '| Frühere Chatnachrichten an den Agenten | 0 | Fakten tragen Werkzeuge und Gedächtnis, nicht der Verlauf |',
      '| Timeout je Modellaufruf | 180 s | Pro Aufruf, pro Agent |',
      '',
      '## Tabellen',
      '',
      '| Tabelle | Enthält |',
      '| --- | --- |',
      '| `users` | Konten, Rollen, Sprache, Land |',
      '| `projects` | Projekte, ihr Workflow-JSON und das `is_system`-Flag |',
      '| `agents` | Agenten und ihre Beschreibungen |',
      '| `skills` | Fähigkeiten und ihren Anweisungstext |',
      '| `tools` | Werkzeuge: Funktionsspezifikation (`description`) und Python-Rumpf (`body`) |',
      '| `agent_skill`, `skill_tool` | Welche Fähigkeiten ein Agent hat, welche Werkzeuge eine Fähigkeit |',
      '| `user_project`, `agent_project` | Projektmitgliedschaft |',
      '| `agent_context_tools` | Vorab laufende Werkzeuge, ihre Überschriften und Argumente |',
      '| `chats`, `messages` | Gespräche und jede Nachricht darin, Werkzeugkarten eingeschlossen |',
      '| `memory` | Notizen mit Schlüssel (Agent, Benutzer) |',
      '| `project_tables` | Welche Speichertabellen einem Projekt gehören |',
      '| `platforms` | LLM-Verbindungen und welche aktiv ist |',
      '| `countries` | Die Länderliste |',
      '',
      'Tabellen, die du im **Speicher** anlegst, sind ebenfalls echte Tabellen und erscheinen hier neben den obigen.',
      '',
      '## Wo was liegt',
      '',
      '```text',
      'backend/app/core/       Agentenschleife, Werkzeugausführung, Delegation, LLM-Client, Auth',
      'backend/app/models/     SQLAlchemy-Modelle',
      'backend/app/routers/    REST- + WebSocket-API',
      'backend/app/schemas/    Request-/Response-Modelle',
      'backend/app/system_management.py   die manage_*-Werkzeuge des Project Managers',
      'frontend/.../views/admin/    Projekte, Fähigkeiten, Werkzeuge, Speicher, Benutzer, Einstellungen, Dokumentation',
      'frontend/.../views/client/   Projekte und der Chat mit den Agenten',
      'frontend/.../locales/        en, zh, ru, es, fr, de',
      '```',
      '',
      '## Eine Geschäftsdomäne hinzufügen',
      '',
      'Lege Modelle unter `backend/app/models/` an, registriere sie in `app/models/__init__.py`, ergänze Router und Schemas auf dieselbe Weise und erstelle die Tabellen mit `backend/migrate.py`.',
      '',
      'Aber bevorzuge die Speicherbibliothek. Alles, was ein Projekt zur Laufzeit braucht, ist besser als **Werkzeug über dem Speicher** aufgehoben, denn dann können die Menschen, denen das Projekt gehört, es ohne Deployment ändern — genau deshalb liegen Werkzeuge und Fähigkeiten in der Datenbank.',
    ].join('\n'),
  },
]