/**
 * La edición en español de la documentación.
 *
 * Misma forma que `content.ts`: `DOC_GROUPS` rotula los grupos del índice y
 * `DOC_SECTIONS` aporta una entrada por ancla. Los valores de `id` siguen en
 * inglés: son el contrato con `docs/index.ts` y las direcciones del tipo
 * `#doc-overview`, así que no se traducen.
 */
import type { DocGroup, DocSection } from './content'

export const DOC_GROUPS: DocGroup[] = [
  { label: 'Primeros pasos', ids: ['overview', 'quick-start', 'concepts'] },
  {
    label: 'Cómo funciona',
    ids: [
      'run-lifecycle',
      'building-a-project',
      'workflow',
      'agents',
      'skills',
      'tools',
      'context-tools',
      'storage',
      'memory',
      'delegation',
    ],
  },
  {
    label: 'Operación',
    ids: ['chats', 'users-and-access', 'llm-connections', 'system-project'],
  },
  { label: 'Referencia', ids: ['use-cases', 'security', 'operations', 'reference'] },
]

export const DOC_SECTIONS: DocSection[] = [
  {
    id: 'overview',
    title: 'Resumen',
    body: [
      'CerebrumKit es un punto de partida para proyectos agénticos. Ofrece un panel de administración donde los agentes se arman con **habilidades** y **herramientas**, una biblioteca de almacenamiento con tablas de negocio que puedes entregar a esos agentes, y un panel de cliente donde las personas para las que existe el proyecto hablan con ellos.',
      '',
      'Aquí nada pertenece a un negocio concreto. No hay catálogo, ni pedidos, ni tabla de productos. Lo que hay es la maquinaria que todo proyecto así necesita, de modo que un proyecto nuevo empieza en «qué deben hacer los agentes» y no en «cómo ejecuto un bucle de agente».',
      '',
      '## Qué obtienes',
      '',
      '| Pieza | Qué es |',
      '| --- | --- |',
      '| Proyectos | Agrupan miembros, agentes y las tablas de almacenamiento que pueden usar, y sostienen el flujo de trabajo que decide quién responde a un mensaje |',
      '| Agentes | Un nombre, una descripción que es su prompt de sistema y las habilidades que lleva |',
      '| Habilidades | Instrucciones escritas más las herramientas que necesitan |',
      '| Herramientas | Una especificación de función de OpenAI más un cuerpo en Python, ambos guardados en la base de datos |',
      '| Almacenamiento | Tablas que creas en el panel, con importación y exportación de Excel |',
      '| Chats | Un websocket por chat que mueve el bucle del agente y transmite las respuestas |',
      '| Memoria | Notas que un agente escribe sobre un usuario, legibles en sus otros chats |',
      '| Delegación | Un agente entrega una tarea autocontenida a otro agente del proyecto |',
      '| Usuarios y roles | `admin` construye los proyectos, `client` solo ve los suyos |',
      '| Proyecto System | Un proyecto protegido con un agente Project Manager que administra la instalación |',
      '',
      '## La idea en un párrafo',
      '',
      'Un mensaje llega por el websocket del chat. El bucle del agente lee el flujo de trabajo del proyecto, elige el agente o el grupo que debe responder, arma el prompt de sistema con la descripción del agente, sus habilidades y la salida de las herramientas previas, y llama al modelo. Las llamadas a herramientas vuelven como function calls; cada una se ejecuta contra el cuerpo de la herramienta guardado en la base de datos, con los identificadores de proyecto, chat, agente y usuario inyectados, de modo que una herramienta solo puede tocar su propia ejecución. Los resultados vuelven al modelo, y el texto que produce se emite en el chat.',
      '',
      'Como las definiciones de herramientas y habilidades viven en la base de datos y no en el código, editar una en el panel surte efecto en la siguiente ejecución, sin reinicio y sin despliegue.',
    ].join('\n'),
  },
  {
    id: 'quick-start',
    title: 'Inicio rápido',
    body: [
      '## Requisitos',
      '',
      '- Python 3.12+ y Node 20+',
      '- PostgreSQL, o SQLite para un vistazo rápido dejando `DATABASE_URL` en su valor por defecto',
      '',
      '## 1. Base de datos',
      '',
      '```bash',
      'docker compose up -d              # o apunta DATABASE_URL a un servidor existente',
      'createdb cerebrumkit              # si ejecutas Postgres tú mismo',
      '```',
      '',
      '## 2. Backend',
      '',
      '```bash',
      'cd backend',
      'python -m venv venv',
      'venv/Scripts/python.exe -m pip install -r requirements.txt      # Windows',
      '# source venv/bin/activate && pip install -r requirements.txt   # macOS / Linux',
      'cp .env.example .env              # luego define DATABASE_URL, SECRET_KEY,',
      '                                  # DEEPSEEK_* y las cuentas SEED_*',
      'venv/Scripts/python.exe seed_all.py',
      '```',
      '',
      '`seed_all.py` crea las tablas, la lista de países, las cuentas de administrador y de cliente, las herramientas y habilidades generales, y el proyecto System con su agente Project Manager. Cada paso es idempotente, así que volver a ejecutarlo es seguro.',
      '',
      'También copia `DEEPSEEK_*` a la tabla `platforms`, que es sobre lo que realmente corre el sistema. Después de eso, **Ajustes -> Conexiones LLM** es el sitio donde cambiar proveedor, URL base, clave de API o modelo.',
      '',
      '## 3. Frontend',
      '',
      '```bash',
      'cd ../frontend/cerebrumkit-vue',
      'npm install',
      'npm run dev',
      '```',
      '',
      'En Windows también puedes hacer doble clic en `run.ps1`, que arranca los dos servidores; `stop.ps1` los detiene.',
      '',
      '## 4. Iniciar sesión',
      '',
      'Abre <http://localhost:5173> e inicia sesión con el `SEED_ADMIN_EMAIL` / `SEED_PASSWORD` que definiste en `backend/.env`.',
      '',
      '> Cambia las contraseñas de siembra antes de que alguien más pueda llegar a la instalación.',
      '',
      '## 5. Apúntalo a un modelo',
      '',
      'Abre **Ajustes -> Conexiones LLM**. La conexión que el seeder copió de `.env` ya está activa y marcada como **En uso**. Pulsa **Probar**: hace una llamada real pequeña, así que una URL, una clave o un nombre de modelo equivocados aparecen aquí en lugar de a mitad de una ejecución.',
      '',
      '## 6. Primera conversación',
      '',
      'Abre **Proyectos**, elige el proyecto **System**, abre un chat y pregúntale algo al Project Manager. Si responde, la instalación funciona de extremo a extremo.',
      '',
      'Para construir lo tuyo, sigue **Crear un proyecto** más abajo. O pídele al Project Manager que lo haga por ti: para eso está el proyecto System.',
    ].join('\n'),
  },
  {
    id: 'concepts',
    title: 'Conceptos básicos',
    body: [
      'Todo lo demás de esta página es un detalle de uno de estos conceptos.',
      '',
      '| Concepto | Qué es |',
      '| --- | --- |',
      '| **Proyecto** | La unidad de trabajo. Posee un flujo de trabajo, un conjunto de usuarios miembros, un conjunto de agentes y un conjunto de tablas de almacenamiento. |',
      '| **Agente** | Un nombre, una descripción que se convierte en su prompt de sistema y las habilidades que lleva. Responde en los chats de los proyectos a los que pertenece. |',
      '| **Habilidad** | Un bloque de instrucciones escritas más las herramientas que esa instrucción necesita. Adjuntar una habilidad a un agente le da esas herramientas. |',
      '| **Herramienta** | Una especificación de función (lo que ve el modelo) más un cuerpo en Python (lo que se ejecuta de verdad). Ambos son filas de la base de datos. |',
      '| **Herramienta de contexto** | Una herramienta que el agente ejecuta *antes* de leer el mensaje, y cuya salida se coloca en su prompt de sistema. |',
      '| **Flujo de trabajo** | El grafo start / group / stop que decide qué agentes responden a un mensaje y en qué orden. |',
      '| **Tabla de almacenamiento** | Una tabla real de la base de datos creada desde el panel, con descripción en la tabla y en cada columna. |',
      '| **Chat** | Una conversación entre un usuario y los agentes de un proyecto, conducida por websocket. |',
      '| **Memoria** | Una nota que un agente escribe sobre un usuario, con clave (agente, usuario), legible en todos los chats de ese usuario. |',
      '| **Conexión LLM** | Una fila en `platforms`: URL base, clave de API, modelo, temperatura, tokens máximos, pensamiento. Una está activa. |',
      '| **Proyecto System** | El único proyecto que no se puede renombrar ni borrar. Alberga al Project Manager. |',
    ].join('\n'),
  },
  {
    id: 'run-lifecycle',
    title: 'Cómo un mensaje se convierte en respuesta',
    body: [
      'Este es todo el bucle, en orden. Cada paso nombra el archivo que lo hace.',
      '',
      '1. **El usuario envía un mensaje** por el websocket del chat (`backend/app/routers/websocket.py`). Se verifica el token, y el usuario debe poseer realmente el chat: un token válido por sí solo no basta. El mensaje pasa al bucle del agente como tarea en segundo plano, así que una ejecución nunca bloquea el socket.',
      '2. **El bucle carga el flujo de trabajo del proyecto** (`backend/app/core/agent_loop.py`). Encuentra el nodo `start` y recorre el grafo. Una ejecución está limitada a 200 pasos como red de seguridad frente a un flujo mal formado o cíclico.',
      '3. **Un nodo de grupo ejecuta sus agentes**, uno tras otro, en el orden en que se asignaron. Los agentes que faltan se omiten con un aviso en lugar de gastar una llamada en nada.',
      '4. **El prompt de cada agente se arma con cuatro cosas**: `You are {name}. {description}`, donde la descripción *es* el encargo permanente del agente; la salida de sus **herramientas de contexto**, ejecutadas ahora mismo, cada una bajo su propio encabezado (como máximo 24.000 caracteres en total); la **última respuesta del propio agente** en este chat, colocada como el turno anterior para que un seguimiento continúe el trabajo previo en vez de empezar en frío (cola de 2.000 caracteres); y el mensaje entrante.',
      '5. **Se llama al modelo** a través de la conexión LLM activa del sistema. El cliente se reutiliza mientras la configuración que hay detrás no cambie, porque reconstruirlo tira su pool de conexiones HTTP.',
      '6. **Se ejecutan las llamadas a herramientas.** Cada una se comprueba contra el proyecto, el chat, el agente y la herramienta antes de ejecutarse; después el cuerpo se compila y se llama con `project_id`, `chat_id`, `agent_id`, `user_id` y `call_depth` ya en el ámbito (`backend/app/core/tool_exec.py`).',
      '7. **Los resultados vuelven al modelo.** Un resultado de más de 8.000 caracteres se recorta *dentro* de su JSON en lugar de cortarse, porque medio objeto JSON hace que el modelo reemita la misma llamada en vez de responder. El resultado completo se conserva en la tarjeta de la herramienta en el chat.',
      '8. **La respuesta se guarda y se emite.** Las llamadas a herramientas aparecen como tarjetas propias en el historial, y el texto del agente se transmite en la conversación.',
      '9. **Se ejecuta el nodo siguiente** con la salida combinada del grupo anterior como entrada. El último grupo responde al usuario.',
      '',
      'Una ejecución puede detenerse a mitad desde el cliente; la tarea se cancela y el chat vuelve a estar inactivo.',
      '',
      '## Qué ve y qué no ve el agente',
      '',
      '- **No** recibe el historial anterior del chat (`HISTORY_WINDOW` es `0`).',
      '- **Sí** recibe su propia respuesta anterior, todo lo que traen sus herramientas de contexto y lo que devuelvan las herramientas durante la ejecución.',
      '- El recuerdo entre chats es para lo que sirve la **memoria**: un agente escribe una nota con `memory_write` y la lee con `memory_lookup` en cualquier chat posterior con el mismo usuario.',
      '',
      'Esa forma es deliberada. Un historial sin límite desplaza a las herramientas y a la petición actual, y normalmente el agente necesita *un dato que aprendió*, no las palabras de la conversación.',
    ].join('\n'),
  },  {
    id: 'building-a-project',
    title: 'Crear un proyecto',
    body: [
      'Constrúyelo en el panel (**Proyectos -> Crear proyecto**) o pídele al Project Manager en el chat del proyecto System que lo haga por ti. El orden que funciona:',
      '',
      '1. **Almacenamiento** — crea las tablas que posee el proyecto, con una descripción en la tabla y en cada columna. Las herramientas las leen, y el agente ve las descripciones.',
      '2. **Herramientas** — una por cada cosa que un agente deba poder hacer. Escribe el cuerpo en Python si lo sabes, o describe la herramienta y deja que el generador redacte la especificación.',
      '3. **Habilidades** — agrupa las herramientas bajo instrucciones escritas: cuándo usarlas, qué pasar, cómo leer el resultado.',
      '4. **Agentes** — una descripción que es el encargo permanente del agente, más las habilidades que lleva. Opcionalmente, herramientas que se ejecutan antes de cada mensaje.',
      '5. **Proyecto** — asigna las tablas, añade los agentes y cablea el flujo de trabajo para que los mensajes les lleguen.',
      '6. **Usuarios** — crea cuentas de cliente y añádelas al proyecto. Solo ven sus propios proyectos y chats.',
      '',
      'Dos hábitos que compensan:',
      '',
      '- **Escribe las descripciones como si fueran para un colega nuevo.** Las descripciones de tabla, columna, herramienta y habilidad son lo único que el modelo sabe de tus datos. «Valor de vida del cliente en EUR, actualizado cada noche» vale diez líneas de código; «un número» no vale nada.',
      '- **Dale a cada agente un solo trabajo.** Un agente con cuatro habilidades y veinte herramientas hace peor todas ellas que cuatro agentes con una cada uno, porque cada descripción de herramienta compite por la atención del modelo.',
    ].join('\n'),
  },
  {
    id: 'workflow',
    title: 'El flujo de trabajo',
    body: [
      'El flujo de trabajo es un grafo pequeño guardado en el proyecto como JSON. Tiene tres tipos de nodo:',
      '',
      '| Nodo | Qué hace |',
      '| --- | --- |',
      '| `start` | Donde entra un mensaje. Exactamente uno. |',
      '| `group` | Ejecuta los agentes que tiene asignados, uno tras otro, en orden. |',
      '| `stop` | Termina esa ruta. |',
      '',
      'Los `wires` los conectan. La salida combinada de un grupo pasa al nodo siguiente, así que un segundo grupo ve el trabajo del primero como su entrada. La salida del grupo **final** es con lo que se responde al usuario.',
      '',
      '```json',
      '{',
      '  "nodes": [',
      '    { "id": 1, "type": "start", "label": "Start" },',
      '    { "id": 2, "type": "group", "label": "Default Group",',
      '      "agents": [ { "id": 1, "name": "Project Manager" } ] },',
      '    { "id": 3, "type": "stop", "label": "Stop" }',
      '  ],',
      '  "wires": [',
      '    { "id": "1-out->2-in", "fromNode": 1, "fromPort": "1-out", "toNode": 2, "toPort": "2-in" },',
      '    { "id": "2-out->3-in", "fromNode": 2, "fromPort": "2-out", "toNode": 3, "toPort": "3-in" }',
      '  ]',
      '}',
      '```',
      '',
      '## Encadenar agentes',
      '',
      'Dos grupos cableados en secuencia es como se construye una tubería: un agente de investigación que recopila, luego un agente de redacción que esboza, luego un agente de revisión que comprueba. Cada grupo ve lo que produjo el anterior.',
      '',
      'Mantén las cadenas cortas. Cada grupo es una ida y vuelta completa al modelo con su propio presupuesto de herramientas, así que una cadena de cinco etapas son cinco ocasiones de perder el hilo y cinco veces la latencia.',
    ].join('\n'),
  },
  {
    id: 'agents',
    title: 'Agentes',
    body: [
      'Un agente es un nombre, una descripción y un conjunto de habilidades.',
      '',
      '**La descripción es el prompt de sistema.** No es documentación. Escríbela como un encargo permanente: quién es este agente, de qué es responsable, cómo debe comportarse, qué debe rechazar. El bucle la envuelve como `You are {name}. {description}` y añade una instrucción breve para que sea útil, conciso y económico con las herramientas.',
      '',
      '**Las habilidades traen las herramientas.** Un agente no tiene una lista de herramientas directa; tiene habilidades, y cada habilidad lleva herramientas. Por eso añadir una capacidad significa adjuntar una habilidad en lugar de marcar doce casillas.',
      '',
      '**Las herramientas de contexto** (opcionales) son herramientas que el agente ejecuta por su cuenta antes de leer el mensaje. Úsalas para lo que se sabe de antemano y siempre hace falta: la fecha actual, el perfil del usuario, un catálogo de productos. Cada resultado se coloca en el prompt de sistema bajo un encabezado que escribes tú. Ver **Herramientas de contexto** más abajo.',
      '',
      '**Activo** es solo un interruptor de apagado: un agente inactivo se omite y sus habilidades no se pueden usar a través de él.',
      '',
      '## Una buena descripción',
      '',
      '```text',
      'Eres el agente de soporte de una tienda online. Respondes preguntas sobre',
      'pedidos, entregas y devoluciones. Busca pedidos con order_lookup — nunca pidas',
      'al cliente un número de pedido que puedas encontrar en su cuenta. Si se pide un',
      'reembolso, comprueba el plazo de devolución antes de prometer nada. Si la',
      'petición es sobre un producto que no ves en el catálogo, dilo y ofrece pasarla',
      'a un compañero.',
      '```',
      '',
      'Fíjate en lo que hace: nombra las herramientas, marca los límites y dice qué hacer cuando se atasca. Una descripción de «agente de soporte servicial» produce un agente servicial que se inventa números de pedido.',
    ].join('\n'),
  },
  {
    id: 'skills',
    title: 'Habilidades',
    body: [
      'Una habilidad es una instrucción escrita más las herramientas que esa instrucción necesita. Dale la habilidad al agente y las herramientas vienen con ella.',
      '',
      'El texto de la habilidad es markdown y se coloca en el prompt de sistema del agente. Es el sitio para el conocimiento procedimental que no cabe en la descripción del agente:',
      '',
      '- **Cuándo usar esta habilidad** — el disparador, para que el agente la elija en el momento correcto.',
      '- **Instrucciones** — los pasos, en orden.',
      '- **Ejemplos** — una llamada y la forma de un buen resultado.',
      '- **Notas y trampas** — el error que, si no, el agente cometería siempre.',
      '',
      'Las habilidades sembradas son buenos modelos que copiar. **«System Administration»** agrupa las herramientas `manage_*` con las reglas para usarlas; **«Delegate a Self-Contained Task to Another Agent»** es un ejemplo completo y resuelto del formato.',
      '',
      'Las habilidades se reutilizan entre agentes y proyectos. Si dos agentes necesitan el mismo procedimiento, escríbelo una vez.',
    ].join('\n'),
  },
  {
    id: 'tools',
    title: 'Herramientas',
    body: [
      'Una herramienta tiene dos mitades, ambas guardadas en la fila de la herramienta:',
      '',
      '| Campo | Qué contiene |',
      '| --- | --- |',
      '| `description` | La especificación de función de OpenAI como JSON: el nombre, la descripción que lee el modelo y los parámetros |',
      '| `body` | El Python que se ejecuta, que define una función con el mismo nombre que la especificación |',
      '',
      'El botón **Generar** del panel redacta ambas a partir de una descripción en lenguaje natural, usando el modelo configurado en Ajustes. Revisa lo que escribe, sobre todo un cuerpo; ver la nota de seguridad más abajo.',
      '',
      '## La especificación de función',
      '',
      '```json',
      '{',
      '  "type": "function",',
      '  "function": {',
      '    "name": "order_lookup",',
      '    "description": "Look up one order by its id. Returns status, items and delivery date.",',
      '    "parameters": {',
      '      "type": "object",',
      '      "properties": {',
      '        "order_id": { "type": "integer", "description": "The order id." }',
      '      },',
      '      "required": ["order_id"]',
      '    }',
      '  }',
      '}',
      '```',
      '',
      'Escribe la descripción para el modelo, no para una persona: di qué devuelve y di qué *no* hace, para que el modelo no tire de ella por error.',
      '',
      '## El cuerpo',
      '',
      'El cuerpo define una función cuyo nombre debe coincidir con `function.name`. Se ejecuta con los identificadores de la ejecución ya en el ámbito:',
      '',
      '| Variable | Qué es |',
      '| --- | --- |',
      '| `project_id` | El proyecto al que pertenece la ejecución |',
      '| `chat_id` | El chat al que pertenece la ejecución |',
      '| `agent_id` | El agente que llamó a la herramienta |',
      '| `user_id` | El **propietario del chat**, no quien escribió, ya que un administrador puede publicar en el chat de otro usuario |',
      '| `call_depth` | `0` para una ejecución iniciada por una persona, `1` para una delegada, y así sucesivamente |',
      '',
      'Los suministra el servidor y nunca deben declararse como parámetros: un modelo que pudiera pasar `project_id` podría leer cualquier proyecto.',
      '',
      '```python',
      'def order_lookup(order_id: int):',
      '    from app.core.database import SessionLocal',
      '    from sqlalchemy import text',
      '',
      '    db = SessionLocal()',
      '    try:',
      '        row = db.execute(',
      '            text("SELECT id, status, delivered_at FROM orders "',
      '                 "WHERE id = :oid AND project_id = :pid"),',
      '            {"oid": order_id, "pid": project_id},',
      '        ).mappings().first()',
      '        if row is None:',
      '            return f"No order {order_id} in this project."',
      '        return dict(row)',
      '    finally:',
      '        db.close()',
      '```',
      '',
      'Dos reglas que mantienen fiables las herramientas:',
      '',
      '- **Devuelve una frase, no una excepción.** Un error lanzado se convierte en una cadena que el modelo lee; si lo capturas, puedes decir *por qué* falló.',
      '- **Acota cada consulta a la ejecución.** Filtra por `project_id` (y el usuario) para que una herramienta solo pueda tocar los datos que recibió.',
      '',
      '> **Seguridad.** El cuerpo de una herramienta es Python arbitrario, compilado y ejecutado con todos los builtins. Deliberadamente no está en una caja de arena, porque las herramientas incluidas importan `requests`, SQLAlchemy y elementos internos de la app. La consecuencia es que escribir una herramienta equivale a ejecutar código en el servidor: mantén los endpoints de herramientas solo para administradores y revisa un cuerpo generado como revisarías código fuente.',
    ].join('\n'),
  },
  {
    id: 'context-tools',
    title: 'Herramientas de contexto',
    body: [
      'Parte de lo que un agente necesita se sabe antes de leer el mensaje: el entorno en el que corre, el perfil del usuario, el catálogo con el que trabaja. Esas consultas no dependen de cómo esté redactado el mensaje, así que dejárselas al modelo cuesta una ronda de herramienta y se omite siempre que el modelo decide que ya sabe bastante.',
      '',
      'Una **herramienta de contexto** convierte esa consulta en parte de cómo arranca el agente. La herramienta se ejecuta y su salida se coloca en el prompt de sistema del agente bajo el encabezado que escribes.',
      '',
      'Solo puede elegirse una herramienta que el agente ya tenga, a través de una habilidad. Para cada una defines:',
      '',
      '| Ajuste | Significado |',
      '| --- | --- |',
      '| Comentario | El encabezado escrito sobre la salida, para que el agente sepa qué está mirando |',
      '| Argumentos | Un objeto JSON de argumentos, para una herramienta que los necesite; vacío para una que no recibe ninguno |',
      '| Orden | Qué aparece antes en el prompt |',
      '',
      'Todo el bloque está limitado a 24.000 caracteres. Una entrada que ya no cabe se descarta y se cuenta en lugar de cortarse por la mitad, porque medio objeto JSON invita al modelo a llamar otra vez a la herramienta para rellenar el hueco.',
      '',
      'Usa las herramientas de contexto con moderación. Se ejecutan en **cada** mensaje, así que una lenta añade su latencia a todos los turnos, y una grande compite con la petición real por la atención del modelo.',
    ].join('\n'),
  },  {
    id: 'storage',
    title: 'Almacenamiento',
    body: [
      'El almacenamiento es una biblioteca de tablas de negocio que creas desde el panel, sin escribir una migración. Cada tabla es una tabla real en la base de datos.',
      '',
      'Una tabla lleva:',
      '',
      '- Un **nombre** y una **descripción** que el agente puede leer.',
      '- **Columnas**, cada una con un tipo y una descripción.',
      '- Un conjunto de **proyectos** a los que está asignada. Una herramienta solo puede alcanzar una tabla que posea su proyecto.',
      '',
      'Las columnas se añaden y se modifican desde el panel, y la tabla subyacente se cambia en consecuencia. Las filas se pueden editar a mano, y una tabla se puede **importar desde** y **exportar a** Excel: la importación previsualiza las primeras filas para que veas el mapeo antes de confirmar.',
      '',
      '## Por qué importan las descripciones',
      '',
      'El agente nunca ve tu esquema. Ve la descripción de la tabla y las descripciones de las columnas, y decide con ellas si consultar y cómo. Una tabla llamada `t1` con una columna llamada `val` es invisible para él. `customer_orders` con `delivered_at — cuándo llegó el paquete al cliente; NULL mientras está en tránsito` sí sirve.',
      '',
      '## Dónde encaja',
      '',
      'Dale a un proyecto sus tablas y luego escribe herramientas que las lean y las escriban. Esta es la forma habitual de un proyecto real: los datos de negocio viven en el almacenamiento y las herramientas son los verbos que el agente puede ejecutar sobre ellos.',
      '',
      'Las tablas creadas fuera del panel (añadiendo un modelo de SQLAlchemy y ejecutando `migrate.py`) también se pueden asignar a un proyecto desde la pantalla de almacenamiento.',
    ].join('\n'),
  },
  {
    id: 'memory',
    title: 'Memoria',
    body: [
      'La memoria es cómo un agente recuerda un dato sobre una persona entre chats.',
      '',
      'Una nota tiene como clave **(agente, usuario)**, no el chat. Así, una nota que el agente de soporte escribe el lunes es legible por el mismo agente el viernes, y no es legible por otro agente; eso importa porque los agentes tienen trabajos distintos y cosas distintas que merece la pena recordar.',
      '',
      'Dos herramientas hacen el trabajo:',
      '',
      '| Herramienta | Qué hace |',
      '| --- | --- |',
      '| `memory_write` | Guardar o actualizar una nota sobre el usuario actual |',
      '| `memory_lookup` | Leer lo que se sabe del usuario actual |',
      '',
      'Ambas vienen con la habilidad sembrada **«Context & Memory Awareness»**. Adjúntala a cualquier agente que deba arrastrar conocimiento.',
      '',
      'La memoria no es un historial. Es para datos duraderos — una preferencia, una restricción, un asunto pendiente — y el agente decide qué merece la pena conservar. Para la conversación en sí, el agente tiene su última respuesta; para todo lo demás, consulta.',
    ].join('\n'),
  },
  {
    id: 'delegation',
    title: 'Delegación',
    body: [
      'Un agente puede entregar una tarea autocontenida a otro agente del mismo proyecto y usar la respuesta.',
      '',
      'La herramienta es `call_agent`, y viene en la habilidad sembrada **«Delegate a Self-Contained Task to Another Agent»**, que además es la mejor documentación del patrón, así que léela en la pantalla de habilidades.',
      '',
      'La propiedad importante: **el otro agente no ve nada de tu conversación.** Ni el mensaje del usuario, ni tus herramientas, ni lo que encontraste. El `message` que pasas debe llevar por tanto toda la petición: contexto, entregable, restricciones, formato esperado.',
      '',
      'Barreras que lo mantienen sensato:',
      '',
      '- La delegación puede llegar a **3 agentes de profundidad**. Dos agentes que se llaman entre sí se detienen en lugar de girar para siempre.',
      '- Una ejecución delegada recibe un presupuesto de herramientas menor (**8 rondas**) que una iniciada por una persona, porque tiene que responder dentro del turno de quien la llama.',
      '- Una ejecución delegada que no termina a tiempo devuelve una frase que lo explica, y quien la llamó la lee como cualquier otro resultado de herramienta.',
      '',
      'La delegación no es un privilegio, no forma parte de la administración del sistema. Cualquier agente de un proyecto puede pasar trabajo a otro de forma útil, así que da la habilidad a quien la necesite.',
    ].join('\n'),
  },
  {
    id: 'chats',
    title: 'Chats y el panel de cliente',
    body: [
      'Un chat pertenece a un usuario y a un proyecto. Su websocket es lo que mueve el bucle: el cliente envía un mensaje y el servidor transmite de vuelta estados, indicadores de escritura, tarjetas de herramientas y respuestas.',
      '',
      'En el historial verás:',
      '',
      '- El **mensaje del usuario**, una vez.',
      '- Una **tarjeta de herramienta** por llamada, con la entrada y la salida, para que una respuesta equivocada se pueda rastrear hasta la llamada que la produjo.',
      '- **Mensajes de flujo**: cuando la salida de un agente se convierte en la entrada de otro, ese traspaso también se registra. Están marcados como flujo en lugar de mostrarse como si los hubiera escrito una persona.',
      '- La **respuesta del agente**.',
      '',
      'Una ejecución se puede **detener** a mitad; el chat vuelve a estar inactivo y el trabajo parcial ya guardado permanece en el historial.',
      '',
      '## El panel de cliente',
      '',
      'Los clientes ven **sus propios proyectos y chats, y nada más**. No ven las herramientas, las habilidades, el flujo de trabajo ni las tablas de almacenamiento que hay detrás de lo que usan: solo la conversación. Esa separación es el objetivo: un operador puede reconstruir todo el stack de agentes por debajo sin que quienes lo usan noten nada más que mejores respuestas.',
    ].join('\n'),
  },
  {
    id: 'users-and-access',
    title: 'Usuarios, roles y acceso',
    body: [
      'Hay dos roles.',
      '',
      '| Rol | Puede |',
      '| --- | --- |',
      '| `admin` | Todo: proyectos, agentes, habilidades, herramientas, almacenamiento, usuarios, conexiones LLM. Ve todos los chats. |',
      '| `client` | Sus propios proyectos y sus propios chats. Nada más. |',
      '',
      'Los usuarios se crean en **Usuarios** (o los crea el Project Manager en el chat). Un cliente solo llega a un proyecto al que se le ha añadido.',
      '',
      'Reglas de acceso que conviene conocer:',
      '',
      '- **El autorregistro público siempre crea un cliente.** El rol se toma del servidor, nunca del cuerpo de la petición; si no, cualquiera podría acuñarse una cuenta de administrador.',
      '- **Los roles elevados solo se conceden por los endpoints de administración.**',
      '- **Un chat pertenece a su propietario.** Un no administrador no puede publicar en el chat de otro, suscribirse a él ni cancelar su ejecución.',
      '- **Las peticiones anónimas reciben 401 y el rol incorrecto 403.** Cada router de administración está protegido a nivel de router, así que ningún endpoint individual puede olvidarlo.',
      '- **El inicio de sesión y el registro tienen límite de frecuencia.**',
      '',
      '> Un administrador *puede* publicar en el chat de un cliente. Cuando lo hace, la ejecución actúa igualmente en nombre del propietario del chat: el `user_id` de una herramienta es el propietario, no el administrador que escribió.',
    ].join('\n'),
  },
  {
    id: 'llm-connections',
    title: 'Conexiones LLM',
    body: [
      'El modelo sobre el que corre todo el sistema es una fila de la tabla `platforms`, no un valor de un archivo de configuración. Eso hace que cambiar de proveedor, URL base, clave o modelo sea un cambio de datos que un administrador puede hacer desde el panel en lugar de un despliegue.',
      '',
      '**Ajustes -> Conexiones LLM** las gestiona. Cada fila contiene:',
      '',
      '| Campo | Significado |',
      '| --- | --- |',
      '| Nombre | Una etiqueta, para distinguir dos filas |',
      '| URL base | El endpoint de la API (en blanco usa el valor por defecto del proveedor) |',
      '| Clave de API | La credencial, guardada y mostrada tal como se escribió |',
      '| Modelo | El nombre del modelo que se va a pedir |',
      '| Temperatura | `0`–`2`; en blanco lo deja al proveedor |',
      '| Tokens máximos | Límite superior de la respuesta; en blanco significa sin límite |',
      '| Pensamiento | Pedir a un modelo de razonamiento que piense antes de responder |',
      '',
      '## Cómo se elige una',
      '',
      '1. Se usa la fila marcada como **activa**.',
      '2. Si no hay ninguna activa, se usa la **primera** fila.',
      '3. Si la tabla está vacía, se usan los valores `DEEPSEEK_*` de `.env`, que es como está una instalación recién hecha antes de guardar nada.',
      '',
      'Exactamente una fila está activa a la vez: activar una desmarca las demás. El aviso de la parte superior de la página muestra siempre qué conexión está realmente en vigor, así que nunca tienes que aplicar tú la regla de reserva.',
      '',
      '## Probar',
      '',
      '**Probar** hace una llamada real pequeña contra esa fila e informa de lo que devolvió. Es la forma más rápida de comprobar una clave, una URL o un nombre de modelo, y merece la pena pulsarlo después de cualquier edición, porque una conexión mala aparece mucho más tarde como una ejecución fallida.',
      '',
      'Guardar una edición surte efecto en la **siguiente ejecución**, sin reinicio. Los clientes se reutilizan mientras la configuración que hay detrás no cambie, así que cambiar de proveedor no tira los pools de conexiones sin motivo.',
      '',
      '> La clave de API se guarda tal como se escribió y se devuelve tal cual: no se enmascara. La pantalla de ajustes es solo para administradores exactamente por eso: quien puede leer la lista puede gastar contra la cuenta que hay detrás.',
    ].join('\n'),
  },  {
    id: 'system-project',
    title: 'El proyecto System y el Project Manager',
    body: [
      'Un proyecto es especial. Está marcado como `is_system`, lo que significa que su propia fila no se puede renombrar ni borrar, así que el agente que vive en él siempre tiene casa. Todo lo de *dentro* sigue siendo editable, y eso es lo que hace que el arreglo funcione.',
      '',
      'Alberga al agente **Project Manager**, que lleva la habilidad **«System Administration»** y la habilidad de delegación. Sus herramientas son:',
      '',
      '| Herramienta | Qué gestiona |',
      '| --- | --- |',
      '| `manage_users` | Listar, leer, crear, actualizar y activar o desactivar usuarios |',
      '| `manage_projects` | Proyectos, sus miembros, sus agentes y su flujo de trabajo |',
      '| `manage_agents` | Agentes y las habilidades que llevan |',
      '| `manage_skills` | Habilidades y las herramientas que llevan |',
      '| `manage_tools` | Herramientas, incluida la generación de especificación y cuerpo desde una descripción |',
      '| `manage_storage` | Tablas de almacenamiento, sus columnas y sus filas |',
      '| `call_agent` | Entregar una tarea a otro agente del proyecto |',
      '',
      'Así que la instalación se puede administrar **pidiéndolo en el chat**. Crear un usuario, levantar un proyecto, escribir una herramienta, cablear un flujo de trabajo: el Project Manager lo hace por la misma capa de servicios que usa el panel, no por la API REST.',
      '',
      'También es la forma más rápida de aprender el sistema: pregunta qué existe y mira qué llamadas a herramientas vuelven.',
      '',
      'Barreras que conviene conocer: el Project Manager no puede borrar el proyecto System, no puede salir de él ni puede quitarse su propio proyecto de origen o sus propias habilidades, así que no puedes dejarte fuera de la administración sin querer.',
    ].join('\n'),
  },
  {
    id: 'use-cases',
    title: 'Casos de uso',
    body: [
      'CerebrumKit es un punto de partida, así que esto son formas y no productos acabados. Cada caso es la misma maquinaria con otra biblioteca de almacenamiento y otro conjunto de herramientas.',
      '',
      '## 1. Un servicio de soporte que responde con tus propios datos',
      '',
      'El **almacenamiento** guarda `customers`, `orders` y `articles`. Las **herramientas** buscan un pedido por id, encuentran un cliente por correo y buscan en los artículos de ayuda. Un agente de soporte lleva una habilidad que le dice: identifica primero al cliente, no cites nunca una fecha de entrega que no hayas leído del pedido y escala cualquier cosa sobre un reembolso.',
      '',
      'El panel de cliente es tu bandeja de soporte. Lo valioso son las descripciones de las herramientas y el texto de la habilidad, no el modelo: un modelo genérico más tu tabla de pedidos supera a un modelo excelente sin datos.',
      '',
      '## 2. Una consola de operaciones sobre un sistema de negocio',
      '',
      'Tus datos reales viven en otro sistema detrás de una API HTTP. La herramienta sembrada **`api_call`** hace peticiones; escribe herramientas finas por endpoint — `get_invoice`, `list_open_tickets`, `approve_leave` — para que el agente trabaje con verbos con nombre en lugar de URL crudas.',
      '',
      'Dos agentes encadenados en el flujo de trabajo: uno recopila y resume, otro redacta la acción. Una persona lee el borrador en el chat antes de que se apruebe nada. Primero herramientas de solo lectura; añade las rutas de escritura cuando te fíes de las descripciones.',
      '',
      '## 3. Ventas internas: investigar antes de la llamada',
      '',
      'Un agente de investigación con una habilidad `web_search` y una herramienta `company_lookup` sobre una tabla `accounts`. Su **herramienta de contexto** precarga la ficha de la cuenta antes de cada mensaje, así que «¿con qué abro la conversación?» se responde con datos reales en lugar de preguntarse.',
      '',
      'Aquí la delegación se gana el sitio: el agente principal pasa «resume los dos últimos trimestres» a un agente de investigación y usa la respuesta, sin que el investigador vea todo el hilo.',
      '',
      '## 4. Entrada de documentos en el back office',
      '',
      'Los operadores pegan o suben el texto extraído de un documento a un chat. Las herramientas lo cotejan con tablas de referencia del almacenamiento y proponen los asientos. Una cola de aprobación no es más que un segundo proyecto cuyo agente puede escribir.',
      '',
      'La importación de Excel en una tabla de almacenamiento es como entran los datos de referencia; la exportación es como un revisor se lleva el resultado.',
      '',
      '## 5. Un asistente productizado para tus propios clientes',
      '',
      'Un proyecto por cliente, cada uno con sus tablas de almacenamiento y sus agentes, y cuentas de cliente acotadas a su proyecto. El panel de administración es tu back office; el panel de cliente es el producto.',
      '',
      'Como un cliente solo ve sus propios chats y nunca las herramientas ni las tablas que hay detrás, puedes reconstruir las habilidades de un agente entre sesiones sin que el cliente note nada más que el cambio en las respuestas.',
      '',
      '## 6. Administrar la plataforma hablando con ella',
      '',
      'Incluso sin ningún dominio de negocio, el proyecto System es útil: pide al Project Manager que cree un usuario, levante un proyecto, escriba una herramienta a partir de una descripción, la adjunte a una habilidad y la cablee en un flujo de trabajo. Luego lee las tarjetas de herramientas del historial para ver exactamente qué hizo.',
      '',
      'Para quien está aprendiendo el sistema, es el recorrido más rápido posible, y es un ejemplo funcional de todo el diseño.',
    ].join('\n'),
  },
  {
    id: 'security',
    title: 'Seguridad y confianza',
    body: [
      'Merece la pena enunciar el modelo de confianza con claridad, porque dos de sus propiedades son deliberadas y una de ellas es afilada.',
      '',
      '## El cuerpo de una herramienta es ejecución de código',
      '',
      'Los cuerpos de las herramientas se compilan y se ejecutan con todos los builtins. **No están en una caja de arena**, porque las herramientas incluidas importan `requests`, SQLAlchemy y elementos internos de la app, y una pasa a la base de datos SQL escrito por el modelo: una caja de arena con builtins restringidos las rompería todas.',
      '',
      'Así que: escribir una herramienta equivale a ejecutar código en el servidor. Los endpoints de herramientas de administración deben seguir siendo solo para administradores, y `tools.body` debería revisarse como revisarías un commit. Por eso el botón **Generar** redacta un cuerpo pero no lo instala en silencio.',
      '',
      'Aun así, quien llama no puede alcanzar una herramienta que no esté adjunta a su agente, y al cuerpo de una herramienta el modelo no puede darle un `project_id`: los identificadores de la ejecución los suministra el servidor.',
      '',
      '## Control de acceso',
      '',
      '| Regla | Dónde se aplica |',
      '| --- | --- |',
      '| Los routers de administración son solo para administradores | Dependencia a nivel de router, ningún endpoint puede olvidarla |',
      '| El registro no puede crear un administrador | El rol se fija en el servidor, nunca se lee del cuerpo |',
      '| Un chat pertenece a su propietario | Se comprueba en las rutas REST y otra vez en el websocket |',
      '| El historial no se puede leer entre usuarios | Los no administradores siempre se filtran a sus propias filas |',
      '| Inicio de sesión y registro con límite de frecuencia | Limitador de ventana deslizante por cliente |',
      '',
      '## Credenciales',
      '',
      '- Las claves de API de LLM se guardan en la base de datos y se muestran **sin enmascarar** en Ajustes, que es solo para administradores por diseño.',
      '- `SECRET_KEY` firma los JWT. La app avisa al arrancar si sigue en el valor de ejemplo: cámbialo antes de que alguien más llegue a la instalación.',
      '- Las cuentas sembradas tienen contraseñas sembradas. Cámbialas.',
      '- `.env` no se versiona. Que siga así.',
      '',
      '## Dónde se trata la salida del modelo como no confiable',
      '',
      '- La exportación a hoja de cálculo neutraliza la inyección de fórmulas, así que una celda que empiece por `=` no se ejecuta en Excel.',
      '- Los resultados de herramientas se truncan antes de llegar al modelo, y se recortan dentro de su JSON en lugar de cortarse.',
      '- Las ejecuciones están limitadas en pasos, rondas de herramientas, profundidad de delegación y duración de herramienta, así que ninguna ejecución puede girar sin fin.',
    ].join('\n'),
  },
  {
    id: 'operations',
    title: 'Operación',
    body: [
      '## Ejecutarlo',
      '',
      '```bash',
      '# backend',
      'cd backend && venv/Scripts/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8000',
      '',
      '# frontend',
      'cd frontend/cerebrumkit-vue && npm run dev',
      '```',
      '',
      'En Windows, `run.ps1` arranca los dos y `stop.ps1` los detiene. Para producción, `DEPLOY.md` cubre nginx, systemd y una ruta de reconstrucción que mantiene las filas de la base de datos (herramientas, habilidades, agentes) al paso con el código.',
      '',
      '## Cambios en la base de datos',
      '',
      '`backend/migrate.py` crea las tablas que falten y añade las columnas que falten. Es seguro volver a ejecutarlo: así se levanta una instalación nueva y así se convierte en tabla un modelo nuevo en `backend/app/models/`.',
      '',
      '## Siembra',
      '',
      '| Script | Qué hace |',
      '| --- | --- |',
      '| `seed_all.py` | Todo lo de abajo, en orden: el único comando que necesita una instalación nueva |',
      '| `seed.py` | Las cuentas de administrador y de cliente desde las variables `SEED_*` |',
      '| `seed_countries.py` | La lista de países |',
      '| `seed_general_tools.py` | Las herramientas generales y sus habilidades |',
      '| `seed_system_project.py` | El proyecto System y el Project Manager |',
      '',
      'Todos son idempotentes — las filas se emparejan por nombre y se actualizan en su sitio —, así que volver a ejecutarlos tras editar el cuerpo de una herramienta empuja la corrección.',
      '',
      '## Mover datos entre instalaciones',
      '',
      '`export_for_deploy.py` escribe los datos del proyecto y `load_for_deploy.py` los lee. Úsalos para mover herramientas, habilidades, agentes y definiciones de almacenamiento de una instalación de desarrollo a una desplegada.',
      '',
      '## Registros',
      '',
      'El ayudante `run.ps1` escribe `backend.log` / `backend.err.log` y `frontend.log` / `frontend.err.log` junto a la raíz del proyecto. Una ejecución fallida se registra con el id del chat, así que un informe de «no respondió» se puede rastrear hasta la ejecución que falló.',
      '',
      '## Desplegar un cambio en los agentes',
      '',
      'La mayoría de los cambios de agentes no necesitan despliegue alguno: edita la herramienta, la habilidad o el agente en el panel y surte efecto en la siguiente ejecución. Solo vuelves a desplegar cuando cambia el **código**: el bucle del agente, un router, un modelo.',
    ].join('\n'),
  },
  {
    id: 'reference',
    title: 'Referencia',
    body: [
      '## Límites',
      '',
      'Cada tope existe para que una ejecución desbocada no consuma el sistema. Están en `backend/app/core/agent_loop.py`.',
      '',
      '| Límite | Valor | Por qué |',
      '| --- | --- | --- |',
      '| Rondas de llamadas a herramientas por turno de agente | 100 | Evita que un modelo se ponga en bucle con las herramientas |',
      '| Rondas de llamadas en una ejecución delegada | 8 | Debe responder dentro del turno de quien la llama |',
      '| Profundidad de delegación | 3 | Dos agentes que se llaman entre sí se detienen |',
      '| Tiempo de espera por llamada a herramienta | 60 s | Una herramienta que nunca vuelve no puede colgar la ejecución |',
      '| Tiempo de espera por llamada delegada | 300 s | Una ejecución anidada necesita más que una herramienta normal |',
      '| Resultado de herramienta que llega al modelo | 8.000 caracteres | Una respuesta grande de API no puede comerse la ventana de contexto |',
      '| Tarjeta de herramienta guardada en el chat | 100.000 caracteres | La tarjeta es para una persona y aun así está acotada |',
      '| Herramientas de contexto previas, total | 24.000 caracteres | Mantiene el prompt de sistema en proporción |',
      '| Última respuesta del propio agente inyectada | 2.000 caracteres | Basta para la conclusión, no para una página entera de JSON |',
      '| Pasos de flujo de trabajo por ejecución | 200 | Red de seguridad para un flujo mal formado o cíclico |',
      '| Mensajes anteriores del chat enviados al agente | 0 | Los hechos los llevan las herramientas y la memoria, no el historial |',
      '| Tiempo de espera por llamada al modelo | 180 s | Por llamada, por agente |',
      '',
      '## Tablas',
      '',
      '| Tabla | Contiene |',
      '| --- | --- |',
      '| `users` | Cuentas, roles, idioma, país |',
      '| `projects` | Proyectos, su JSON de flujo de trabajo y la marca `is_system` |',
      '| `agents` | Agentes y sus descripciones |',
      '| `skills` | Habilidades y su texto de instrucciones |',
      '| `tools` | Herramientas: especificación de función (`description`) y cuerpo en Python (`body`) |',
      '| `agent_skill`, `skill_tool` | Qué habilidades tiene un agente y qué herramientas tiene una habilidad |',
      '| `user_project`, `agent_project` | Pertenencia a proyectos |',
      '| `agent_context_tools` | Herramientas previas, sus encabezados y argumentos |',
      '| `chats`, `messages` | Conversaciones y cada mensaje, tarjetas de herramientas incluidas |',
      '| `memory` | Notas con clave (agente, usuario) |',
      '| `project_tables` | Qué tablas de almacenamiento posee un proyecto |',
      '| `platforms` | Conexiones LLM y cuál está activa |',
      '| `countries` | La lista de países |',
      '',
      'Las tablas que creas en **Almacenamiento** también son tablas reales y aparecen aquí junto a las de arriba.',
      '',
      '## Dónde vive cada cosa',
      '',
      '```text',
      'backend/app/core/       bucle del agente, ejecución de herramientas, delegación, cliente LLM, auth',
      'backend/app/models/     modelos de SQLAlchemy',
      'backend/app/routers/    API REST + websocket',
      'backend/app/schemas/    modelos de petición y respuesta',
      'backend/app/system_management.py   las herramientas manage_* que usa el Project Manager',
      'frontend/.../views/admin/    Proyectos, Habilidades, Herramientas, Almacenamiento, Usuarios, Ajustes, Documentación',
      'frontend/.../views/client/   Proyectos y el chat con los agentes',
      'frontend/.../locales/        en, zh, ru, es, fr, de',
      '```',
      '',
      '## Añadir un dominio de negocio',
      '',
      'Añade modelos en `backend/app/models/`, regístralos en `app/models/__init__.py`, añade routers y esquemas de la misma forma, y crea las tablas con `backend/migrate.py`.',
      '',
      'Pero prefiere la biblioteca de almacenamiento. Todo lo que un proyecto necesita en tiempo de ejecución está mejor como **herramienta sobre el almacenamiento**, porque así las personas dueñas del proyecto pueden cambiarlo sin un despliegue: esa es la razón de que las herramientas y las habilidades vivan en la base de datos.',
    ].join('\n'),
  },
]