/**
 * L’édition française de la documentation.
 *
 * Même forme que `content.ts` : `DOC_GROUPS` nomme les groupes du sommaire et
 * `DOC_SECTIONS` fournit une entrée par ancre. Les `id` restent en anglais :
 * c’est le contrat avec `docs/index.ts` et les adresses du type `#doc-overview`,
 * ils ne se traduisent donc pas.
 */
import type { DocGroup, DocSection } from './content'

export const DOC_GROUPS: DocGroup[] = [
  { label: 'Premiers pas', ids: ['overview', 'quick-start', 'concepts'] },
  {
    label: 'Comment ça marche',
    ids: [
      'run-lifecycle',
      'building-a-project',
      'workflow',
      'agents',
      'skills',
      'tools',
      'context-tools',
      'storage',
      'memory',
      'delegation',
    ],
  },
  {
    label: 'Exploitation',
    ids: ['chats', 'users-and-access', 'llm-connections', 'system-project'],
  },
  { label: 'Référence', ids: ['use-cases', 'security', 'operations', 'reference'] },
]

export const DOC_SECTIONS: DocSection[] = [
  {
    id: 'overview',
    title: 'Vue d’ensemble',
    body: [
      'CerebrumKit est un point de départ pour des projets agentiques. Il fournit un panneau d’administration où les agents se composent de **compétences** et d’**outils**, une bibliothèque de stockage de tables métier que vous pouvez confier à ces agents, et un panneau client où les personnes à qui le projet s’adresse leur parlent.',
      '',
      'Ici rien n’appartient à un métier particulier. Il n’y a ni catalogue, ni commandes, ni table de produits. Ce qu’on trouve ici, c’est la mécanique dont tout projet de ce genre a besoin : un nouveau projet commence donc à « que doivent faire les agents » plutôt qu’à « comment j’exécute une boucle d’agent ».',
      '',
      '## Ce que vous obtenez',
      '',
      '| Élément | Ce que c’est |',
      '| --- | --- |',
      '| Projets | Regroupent des membres, des agents et les tables de stockage qu’ils peuvent utiliser, et portent le flux de travail qui décide qui répond à un message |',
      '| Agents | Un nom, une description qui fait office de prompt système, et les compétences qu’il porte |',
      '| Compétences | Des instructions écrites, plus les outils dont ces instructions ont besoin |',
      '| Outils | Une spécification de fonction OpenAI et un corps Python, tous deux stockés en base |',
      '| Stockage | Des tables que vous créez dans le panneau, avec import et export Excel |',
      '| Chats | Un websocket par chat, qui pilote la boucle d’agent et diffuse les réponses |',
      '| Mémoire | Des notes qu’un agent écrit sur un utilisateur, lisibles dans ses autres chats |',
      '| Délégation | Un agent confie une tâche autonome à un autre agent du projet |',
      '| Utilisateurs et rôles | `admin` construit les projets, `client` ne voit que les siens |',
      '| Projet System | Un projet protégé, abritant un agent Project Manager qui administre l’installation |',
      '',
      '## L’idée en un paragraphe',
      '',
      'Un message arrive sur le websocket du chat. La boucle d’agent lit le flux de travail du projet, choisit l’agent ou le groupe qui doit répondre, construit le prompt système à partir de la description de l’agent, de ses compétences et de la sortie des outils préalables, puis appelle le modèle. Les appels d’outils reviennent sous forme de function calls ; chacun est exécuté contre le corps de l’outil stocké en base, avec les identifiants de projet, de chat, d’agent et d’utilisateur injectés, si bien qu’un outil ne peut jamais toucher que sa propre exécution. Les résultats repartent vers le modèle, et le texte qu’il produit est diffusé dans le chat.',
      '',
      'Comme les définitions d’outils et de compétences vivent en base plutôt que dans le code, en modifier une dans le panneau prend effet à l’exécution suivante, sans redémarrage ni déploiement.',

      '',
      '## Author',
      '![Islomkhon Nizomkhonov](/IslomkhonNizomkhonov.png)',
      '',
      '### Islomkhon Nizomkhonov (小伊)',
      '',
      '- **Formation** : master en informatique, China University of Mining and Technology',
      '- **Compétences clés** : ingénierie logicielle, apprentissage profond, apprentissage automatique, science des données, IoT, maintenance prédictive',
      '',
      'Islomkhon Nizomkhonov est né en 1994 à Tachkent, en Ouzbékistan. Il est ingénieur logiciel senior avec plus de six ans d\'expérience en apprentissage automatique et en maintenance prédictive. Il a travaillé avec plusieurs secteurs et de grandes entreprises, notamment [XCMG (徐工集团)](https://www.xcmg.com/) et [Uztelecom (l\'opérateur national de télécommunications d\'Ouzbékistan)](https://uztelecom.uz/), pour lesquelles il a livré des solutions fondées sur l\'apprentissage profond. Ses recherches portent sur l\'utilisation de réseaux de neurones pour le diagnostic de pannes dans les systèmes IoT industriels. Aujourd\'hui, il se concentre sur les **agents IA**, l\'**ingénierie logicielle pour et avec l\'IA** et l\'**IA digne de confiance**. Si vous souhaitez collaborer ou discuter d\'un cas d\'usage, n\'hésitez pas à le contacter par e-mail à [islomkhon@126.com](mailto:islomkhon@126.com) ou par téléphone au +86 139 1487 4257.\',',
    ].join('\n'),
  },
  {
    id: 'quick-start',
    title: 'Démarrage rapide',
    body: [
      '## Prérequis',
      '',
      '- Python 3.12+ et Node 20+',
      '- PostgreSQL, ou SQLite pour un coup d’œil rapide en laissant `DATABASE_URL` à sa valeur par défaut',
      '',
      '## 1. Base de données',
      '',
      '```bash',
      'docker compose up -d              # ou pointez DATABASE_URL vers un serveur existant',
      'createdb cerebrumkit              # si vous gérez Postgres vous-même',
      '```',
      '',
      '## 2. Backend',
      '',
      '```bash',
      'cd backend',
      'python -m venv venv',
      'venv/Scripts/python.exe -m pip install -r requirements.txt      # Windows',
      '# source venv/bin/activate && pip install -r requirements.txt   # macOS / Linux',
      'cp .env.example .env              # puis définissez DATABASE_URL, SECRET_KEY,',
      '                                  # DEEPSEEK_* et les comptes SEED_*',
      'venv/Scripts/python.exe seed_all.py',
      '```',
      '',
      '`seed_all.py` crée les tables, la liste des pays, les comptes admin et client, les outils et compétences généraux, et le projet System avec son agent Project Manager. Chaque étape est idempotente, donc le relancer est sans danger.',
      '',
      'Il copie aussi `DEEPSEEK_*` dans la table `platforms`, sur laquelle le système tourne réellement. Ensuite, **Paramètres -> Connexions LLM** est l’endroit où changer de fournisseur, d’URL de base, de clé d’API ou de modèle.',
      '',
      '## 3. Frontend',
      '',
      '```bash',
      'cd ../frontend/cerebrumkit-vue',
      'npm install',
      'npm run dev',
      '```',
      '',
      'Sous Windows, vous pouvez aussi double-cliquer sur `run.ps1`, qui démarre les deux serveurs ; `stop.ps1` les arrête.',
      '',
      '## 4. Se connecter',
      '',
      'Ouvrez <http://localhost:5173> et connectez-vous avec les `SEED_ADMIN_EMAIL` / `SEED_PASSWORD` définis dans `backend/.env`.',
      '',
      '> Changez les mots de passe de départ avant que quelqu’un d’autre puisse atteindre l’installation.',
      '',
      '## 5. Pointer vers un modèle',
      '',
      'Ouvrez **Paramètres -> Connexions LLM**. La connexion que le seeder a copiée depuis `.env` est déjà active et marquée **En usage**. Appuyez sur **Tester** : cela fait un petit appel réel, donc une URL, une clé ou un nom de modèle erronés apparaissent ici plutôt qu’au milieu d’une exécution.',
      '',
      '## 6. Premier chat',
      '',
      'Ouvrez **Projets**, choisissez le projet **System**, ouvrez un chat et posez une question au Project Manager. S’il répond, l’installation fonctionne de bout en bout.',
      '',
      'Pour construire votre propre chose, suivez **Construire un projet** plus bas. Ou demandez au Project Manager de le faire pour vous : c’est le but du projet System.',
    ].join('\n'),
  },
  {
    id: 'concepts',
    title: 'Concepts clés',
    body: [
      'Tout le reste de cette page est un détail de l’un de ces concepts.',
      '',
      '| Concept | Ce que c’est |',
      '| --- | --- |',
      '| **Projet** | L’unité de travail. Possède un flux de travail, un ensemble d’utilisateurs membres, un ensemble d’agents et un ensemble de tables de stockage. |',
      '| **Agent** | Un nom, une description qui devient son prompt système, et les compétences qu’il porte. Répond dans les chats des projets auxquels il appartient. |',
      '| **Compétence** | Un bloc d’instructions écrites, plus les outils dont cette instruction a besoin. Attacher une compétence à un agent lui donne ces outils. |',
      '| **Outil** | Une spécification de fonction (ce que voit le modèle) et un corps Python (ce qui s’exécute réellement). Les deux sont des lignes en base. |',
      '| **Outil de contexte** | Un outil que l’agent exécute *avant* de lire le message, et dont la sortie est placée dans son prompt système. |',
      '| **Flux de travail** | Le graphe start / group / stop qui décide quels agents répondent à un message, et dans quel ordre. |',
      '| **Table de stockage** | Une vraie table de base de données créée depuis le panneau, avec une description sur la table et sur chaque colonne. |',
      '| **Chat** | Une conversation entre un utilisateur et les agents d’un projet, pilotée par websocket. |',
      '| **Mémoire** | Une note qu’un agent écrit sur un utilisateur, indexée par (agent, utilisateur), donc lisible dans tous les chats de cet utilisateur. |',
      '| **Connexion LLM** | Une ligne dans `platforms` : URL de base, clé d’API, modèle, température, tokens max, réflexion. Une seule est active. |',
      '| **Projet System** | Le seul projet qui ne peut être ni renommé ni supprimé. Il abrite le Project Manager. |',
    ].join('\n'),
  },
  {
    id: 'run-lifecycle',
    title: 'Comment un message devient une réponse',
    body: [
      'Voici toute la boucle, dans l’ordre. Chaque étape nomme le fichier qui l’exécute.',
      '',
      '1. **L’utilisateur envoie un message** sur le websocket du chat (`backend/app/routers/websocket.py`). Le jeton est vérifié, et l’utilisateur doit réellement posséder le chat : un jeton valide ne suffit pas. Le message est confié à la boucle d’agent comme tâche d’arrière-plan, donc une exécution ne bloque jamais le socket.',
      '2. **La boucle charge le flux de travail du projet** (`backend/app/core/agent_loop.py`). Elle trouve le nœud `start`, puis parcourt le graphe. Une exécution est plafonnée à 200 étapes, filet de sécurité contre un flux mal formé ou cyclique.',
      '3. **Un nœud de groupe exécute ses agents**, un par un, dans l’ordre d’affectation. Les agents manquants sont ignorés avec un avertissement plutôt que de dépenser un appel pour rien.',
      '4. **Le prompt de chaque agent est assemblé** à partir de quatre choses : `You are {name}. {description}`, où la description *est* la mission permanente de l’agent ; la sortie de ses **outils de contexte**, exécutés maintenant, chacun sous son propre titre (24 000 caractères au total au maximum) ; la **dernière réponse de l’agent lui-même** dans ce chat, placée comme le tour précédent pour qu’une relance poursuive le travail antérieur au lieu de repartir à froid (2 000 derniers caractères) ; et le message entrant.',
      '5. **Le modèle est appelé** via la connexion LLM active du système. Le client est réutilisé tant que la configuration derrière lui n’a pas changé, car le reconstruire jette son pool de connexions HTTP.',
      '6. **Les appels d’outils sont exécutés.** Chacun est vérifié contre le projet, le chat, l’agent et l’outil avant de s’exécuter, puis le corps est compilé et appelé avec `project_id`, `chat_id`, `agent_id`, `user_id` et `call_depth` déjà dans la portée (`backend/app/core/tool_exec.py`).',
      '7. **Les résultats repartent vers le modèle.** Un résultat de plus de 8 000 caractères est rogné *à l’intérieur* de son JSON plutôt que coupé, car un demi-objet JSON pousse le modèle à réémettre le même appel au lieu de répondre. Le résultat complet reste sur la carte d’outil dans le chat.',
      '8. **La réponse est enregistrée et diffusée.** Les appels d’outils apparaissent comme des cartes à part dans l’historique, et le texte de l’agent est diffusé dans la conversation.',
      '9. **Le nœud suivant s’exécute** avec la sortie combinée du groupe précédent comme entrée. Le dernier groupe répond à l’utilisateur.',
      '',
      'Une exécution peut être arrêtée en cours de route depuis le client ; la tâche est annulée et le chat redevient inactif.',
      '',
      '## Ce que l’agent voit et ne voit pas',
      '',
      '- Il **ne** reçoit **pas** l’historique antérieur du chat (`HISTORY_WINDOW` vaut `0`).',
      '- Il **reçoit** sa propre réponse précédente, tout ce que rapportent ses outils de contexte, et tout ce que les outils renvoient pendant l’exécution.',
      '- Le rappel entre chats, c’est le rôle de la **mémoire** : un agent écrit une note avec `memory_write` et la relit avec `memory_lookup` dans n’importe quel chat ultérieur avec le même utilisateur.',
      '',
      'Cette forme est délibérée. Un historique sans limite évince les outils et la demande en cours, et l’agent a généralement besoin *d’un fait qu’il a appris*, pas des mots de la conversation.',
    ].join('\n'),
  },  {
    id: 'building-a-project',
    title: 'Construire un projet',
    body: [
      'Construisez-le dans le panneau (**Projets -> Créer un projet**), ou demandez au Project Manager dans le chat du projet System de le faire pour vous. L’ordre qui fonctionne :',
      '',
      '1. **Stockage** — créez les tables que le projet possède, avec une description sur la table et sur chaque colonne. Les outils les lisent, et l’agent voit les descriptions.',
      '2. **Outils** — un par chose qu’un agent doit pouvoir faire. Écrivez le corps Python si vous le connaissez, ou décrivez l’outil et laissez le générateur rédiger la spécification.',
      '3. **Compétences** — regroupez les outils sous des instructions écrites : quand les utiliser, quoi passer, comment lire le résultat.',
      '4. **Agents** — une description qui est la mission permanente de l’agent, plus les compétences qu’il porte. Éventuellement, des outils à exécuter avant chaque message.',
      '5. **Projet** — affectez les tables, ajoutez les agents et câblez le flux de travail pour que les messages les atteignent.',
      '6. **Utilisateurs** — créez des comptes client et ajoutez-les au projet. Ils ne voient que leurs propres projets et chats.',
      '',
      'Deux habitudes qui paient :',
      '',
      '- **Écrivez les descriptions comme pour un nouveau collègue.** Les descriptions de table, de colonne, d’outil et de compétence sont tout ce que le modèle sait de vos données. « Valeur vie client en EUR, actualisée chaque nuit » vaut dix lignes de code ; « un nombre » ne vaut rien.',
      '- **Donnez une seule tâche à un agent.** Un agent avec quatre compétences et vingt outils fait moins bien chacune d’elles que quatre agents avec une chacune, car chaque description d’outil concurrence l’attention du modèle.',
    ].join('\n'),
  },
  {
    id: 'workflow',
    title: 'Le flux de travail',
    body: [
      'Le flux de travail est un petit graphe stocké sur le projet au format JSON. Il comporte trois types de nœuds :',
      '',
      '| Nœud | Ce qu’il fait |',
      '| --- | --- |',
      '| `start` | Là où entre un message. Exactement un. |',
      '| `group` | Exécute les agents qui lui sont affectés, l’un après l’autre, dans l’ordre. |',
      '| `stop` | Termine ce chemin. |',
      '',
      'Les `wires` les relient. La sortie combinée d’un groupe est transmise au nœud suivant, si bien qu’un second groupe voit le travail du premier comme son entrée. La sortie du groupe **final** est ce avec quoi l’utilisateur est servi.',
      '',
      '```json',
      '{',
      '  "nodes": [',
      '    { "id": 1, "type": "start", "label": "Start" },',
      '    { "id": 2, "type": "group", "label": "Default Group",',
      '      "agents": [ { "id": 1, "name": "Project Manager" } ] },',
      '    { "id": 3, "type": "stop", "label": "Stop" }',
      '  ],',
      '  "wires": [',
      '    { "id": "1-out->2-in", "fromNode": 1, "fromPort": "1-out", "toNode": 2, "toPort": "2-in" },',
      '    { "id": "2-out->3-in", "fromNode": 2, "fromPort": "2-out", "toNode": 3, "toPort": "3-in" }',
      '  ]',
      '}',
      '```',
      '',
      '## Enchaîner les agents',
      '',
      'Deux groupes câblés en séquence, c’est ainsi qu’on construit un pipeline : un agent de recherche qui collecte, puis un agent de rédaction qui ébauche, puis un agent de relecture qui vérifie. Chaque groupe voit ce que le précédent a produit.',
      '',
      'Gardez les chaînes courtes. Chaque groupe est un aller-retour complet vers le modèle avec son propre budget d’outils : une chaîne de cinq étages, ce sont cinq occasions de perdre le fil et cinq fois la latence.',
    ].join('\n'),
  },
  {
    id: 'agents',
    title: 'Agents',
    body: [
      'Un agent, c’est un nom, une description et un ensemble de compétences.',
      '',
      '**La description est le prompt système.** Ce n’est pas de la documentation. Écrivez-la comme une mission permanente : qui est cet agent, de quoi il répond, comment il doit se comporter, ce qu’il doit refuser. La boucle l’enveloppe en `You are {name}. {description}` et ajoute une courte consigne pour être utile, concis et économe en outils.',
      '',
      '**Les compétences apportent les outils.** Un agent n’a pas de liste d’outils directe ; il a des compétences, et chaque compétence porte des outils. C’est pourquoi ajouter une capacité consiste à attacher une compétence plutôt qu’à cocher douze cases.',
      '',
      '**Les outils de contexte** (facultatifs) sont des outils que l’agent exécute de lui-même avant de lire le message. Utilisez-les pour ce qui est connaissable à l’avance et toujours nécessaire : la date du jour, le profil de l’utilisateur, un catalogue produits. Chaque résultat est placé dans le prompt système sous un titre que vous écrivez. Voir **Outils de contexte** plus bas.',
      '',
      '**Actif** n’est qu’un interrupteur : un agent inactif est ignoré et ses compétences ne sont pas utilisables à travers lui.',
      '',
      '## Une bonne description',
      '',
      '```text',
      'Tu es l’agent de support d’une boutique en ligne. Tu réponds aux questions sur',
      'les commandes, la livraison et les retours. Cherche les commandes avec',
      'order_lookup — ne demande jamais au client un numéro de commande que tu peux',
      'trouver dans son compte. Si un remboursement est demandé, vérifie le délai de',
      'retour avant de promettre quoi que ce soit. Si la demande porte sur un produit',
      'absent du catalogue, dis-le et propose de la transmettre à un collègue.',
      '```',
      '',
      'Remarquez ce qu’elle fait : elle nomme les outils, pose les limites et dit quoi faire en cas de blocage. Une description « agent de support serviable » produit un agent serviable qui invente des numéros de commande.',
    ].join('\n'),
  },
  {
    id: 'skills',
    title: 'Compétences',
    body: [
      'Une compétence, c’est une instruction écrite plus les outils dont cette instruction a besoin. Donnez la compétence à l’agent et les outils viennent avec.',
      '',
      'Le texte de la compétence est du markdown et est placé dans le prompt système de l’agent. C’est l’endroit du savoir procédural qui ne tient pas dans la description de l’agent :',
      '',
      '- **Quand utiliser cette compétence** — le déclencheur, pour que l’agent la choisisse au bon moment.',
      '- **Instructions** — les étapes, dans l’ordre.',
      '- **Exemples** — un appel et la forme d’un bon résultat.',
      '- **Remarques et pièges** — l’erreur que l’agent ferait sinon à chaque fois.',
      '',
      'Les compétences fournies sont de bons modèles à copier. **« System Administration »** regroupe les outils `manage_*` avec les règles pour les utiliser ; **« Delegate a Self-Contained Task to Another Agent »** est un exemple complet et travaillé du format.',
      '',
      'Les compétences sont réutilisables entre agents et projets. Si deux agents ont besoin de la même procédure, écrivez-la une fois.',
    ].join('\n'),
  },
  {
    id: 'tools',
    title: 'Outils',
    body: [
      'Un outil a deux moitiés, toutes deux stockées sur la ligne de l’outil :',
      '',
      '| Champ | Ce qu’il contient |',
      '| --- | --- |',
      '| `description` | La spécification de fonction OpenAI en JSON : le nom, la description que lit le modèle et les paramètres |',
      '| `body` | Le Python qui s’exécute, définissant une fonction du même nom que la spécification |',
      '',
      'Le bouton **Générer** du panneau rédige les deux à partir d’une description en langage naturel, avec le modèle configuré dans les Paramètres. Relisez ce qu’il écrit, en particulier un corps ; voir la note de sécurité plus bas.',
      '',
      '## La spécification de fonction',
      '',
      '```json',
      '{',
      '  "type": "function",',
      '  "function": {',
      '    "name": "order_lookup",',
      '    "description": "Look up one order by its id. Returns status, items and delivery date.",',
      '    "parameters": {',
      '      "type": "object",',
      '      "properties": {',
      '        "order_id": { "type": "integer", "description": "The order id." }',
      '      },',
      '      "required": ["order_id"]',
      '    }',
      '  }',
      '}',
      '```',
      '',
      'Écrivez la description pour le modèle, pas pour un humain : dites ce que l’outil renvoie, et dites ce qu’il ne fait *pas*, pour que le modèle ne s’en serve pas par erreur.',
      '',
      '## Le corps',
      '',
      'Le corps définit une fonction dont le nom doit correspondre à `function.name`. Elle s’exécute avec les identifiants de l’exécution déjà dans la portée :',
      '',
      '| Variable | Ce que c’est |',
      '| --- | --- |',
      '| `project_id` | Le projet auquel appartient l’exécution |',
      '| `chat_id` | Le chat auquel appartient l’exécution |',
      '| `agent_id` | L’agent qui a appelé l’outil |',
      '| `user_id` | Le **propriétaire du chat**, pas celui qui a écrit, puisqu’un administrateur peut publier dans le chat d’un autre utilisateur |',
      '| `call_depth` | `0` pour une exécution lancée par une personne, `1` pour une exécution déléguée, et ainsi de suite |',
      '',
      'Ces valeurs sont fournies par le serveur et ne doivent jamais être déclarées comme paramètres : un modèle qui pourrait passer `project_id` pourrait lire n’importe quel projet.',
      '',
      '```python',
      'def order_lookup(order_id: int):',
      '    from app.core.database import SessionLocal',
      '    from sqlalchemy import text',
      '',
      '    db = SessionLocal()',
      '    try:',
      '        row = db.execute(',
      '            text("SELECT id, status, delivered_at FROM orders "',
      '                 "WHERE id = :oid AND project_id = :pid"),',
      '            {"oid": order_id, "pid": project_id},',
      '        ).mappings().first()',
      '        if row is None:',
      '            return f"No order {order_id} in this project."',
      '        return dict(row)',
      '    finally:',
      '        db.close()',
      '```',
      '',
      'Deux règles qui rendent les outils fiables :',
      '',
      '- **Renvoyez une phrase, pas une exception.** Une erreur levée devient une chaîne que le modèle lit ; en la rattrapant, vous pouvez dire *pourquoi* cela a échoué.',
      '- **Cadrez chaque requête sur l’exécution.** Filtrez par `project_id` (et l’utilisateur) pour qu’un outil ne puisse jamais toucher que les données qu’on lui a données.',
      '',
      '> **Sécurité.** Le corps d’un outil est du Python arbitraire, compilé et exécuté avec tous les builtins. Il n’est délibérément pas isolé, car les outils fournis importent `requests`, SQLAlchemy et des éléments internes de l’application. La conséquence : écrire un outil équivaut à exécuter du code sur le serveur. Gardez les points d’accès d’outils réservés aux administrateurs, et relisez un corps généré comme vous reliriez du code source.',
    ].join('\n'),
  },
  {
    id: 'context-tools',
    title: 'Outils de contexte',
    body: [
      'Une partie de ce dont un agent a besoin est connaissable avant la lecture du message : l’environnement dans lequel il tourne, le profil de l’utilisateur, le catalogue sur lequel il travaille. Ces lectures ne dépendent pas des mots du message ; les laisser au modèle coûte donc un tour d’outil et est ignoré dès que le modèle estime en savoir assez.',
      '',
      'Un **outil de contexte** fait de cette lecture une partie de la façon dont l’agent démarre. L’outil s’exécute, et sa sortie est placée dans le prompt système de l’agent sous le titre que vous écrivez.',
      '',
      'Seul un outil que l’agent possède déjà — via une compétence — peut être choisi. Pour chacun, vous définissez :',
      '',
      '| Réglage | Signification |',
      '| --- | --- |',
      '| Commentaire | Le titre écrit au-dessus de la sortie, pour que l’agent sache ce qu’il regarde |',
      '| Arguments | Un objet JSON d’arguments, pour un outil qui en a besoin ; vide pour un outil qui n’en prend aucun |',
      '| Ordre | Ce qui apparaît en premier dans le prompt |',
      '',
      'Tout le bloc est plafonné à 24 000 caractères. Une entrée qui ne rentre plus est écartée et comptée plutôt que coupée en deux, car un demi-objet JSON invite le modèle à rappeler l’outil pour combler le trou.',
      '',
      'Utilisez les outils de contexte avec parcimonie. Ils s’exécutent à **chaque** message : un outil lent ajoute sa latence à chaque tour, et un outil volumineux concurrence la demande réelle pour l’attention du modèle.',
    ].join('\n'),
  },  {
    id: 'storage',
    title: 'Stockage',
    body: [
      'Le stockage est une bibliothèque de tables métier que vous créez depuis le panneau, sans écrire de migration. Chaque table est une vraie table de la base de données.',
      '',
      'Une table porte :',
      '',
      '- Un **nom**, et une **description** que l’agent peut lire.',
      '- Des **colonnes**, chacune avec un type et une description.',
      '- Un ensemble de **projets** auxquels elle est affectée. Un outil ne peut atteindre qu’une table que son projet possède.',
      '',
      'Les colonnes s’ajoutent et se modifient depuis le panneau, et la table sous-jacente est modifiée en conséquence. Les lignes se modifient à la main, et une table peut être **importée depuis** et **exportée vers** Excel : l’import prévisualise les premières lignes pour que vous voyiez la correspondance avant de valider.',
      '',
      '## Pourquoi les descriptions comptent',
      '',
      'L’agent ne voit jamais votre schéma. Il voit la description de la table et les descriptions des colonnes, et décide à partir d’elles s’il interroge et comment. Une table nommée `t1` avec une colonne `val` est invisible pour lui. `customer_orders` avec `delivered_at — quand le colis est arrivé chez le client ; NULL pendant le transport` est exploitable.',
      '',
      '## Où cela s’inscrit',
      '',
      'Donnez à un projet ses tables, puis écrivez des outils qui les lisent et les écrivent. C’est la forme habituelle d’un vrai projet : les données métier vivent dans le stockage, et les outils sont les verbes que l’agent est autorisé à exécuter dessus.',
      '',
      'Les tables créées hors du panneau (en ajoutant un modèle SQLAlchemy et en lançant `migrate.py`) peuvent aussi être affectées à un projet depuis l’écran de stockage.',
    ].join('\n'),
  },
  {
    id: 'memory',
    title: 'Mémoire',
    body: [
      'La mémoire, c’est la façon dont un agent se souvient d’un fait sur une personne d’un chat à l’autre.',
      '',
      'Une note est indexée par **(agent, utilisateur)**, pas par chat. Ainsi, une note que l’agent de support écrit le lundi est lisible par le même agent le vendredi — et ne l’est pas par un autre agent ; cela compte, car les agents ont des tâches différentes et des choses différentes qui méritent d’être retenues.',
      '',
      'Deux outils font le travail :',
      '',
      '| Outil | Ce qu’il fait |',
      '| --- | --- |',
      '| `memory_write` | Enregistrer ou mettre à jour une note sur l’utilisateur courant |',
      '| `memory_lookup` | Relire ce qui est connu sur l’utilisateur courant |',
      '',
      'Les deux viennent avec la compétence fournie **« Context & Memory Awareness »**. Attachez-la à tout agent qui doit faire suivre le savoir.',
      '',
      'La mémoire n’est pas un historique. Elle sert aux faits durables — une préférence, une contrainte, un point en suspens — et l’agent décide ce qui mérite d’être gardé. Pour la conversation elle-même, l’agent a sa dernière réponse ; pour tout le reste, il interroge.',
    ].join('\n'),
  },
  {
    id: 'delegation',
    title: 'Délégation',
    body: [
      'Un agent peut confier une tâche autonome à un autre agent du même projet et utiliser la réponse.',
      '',
      'L’outil s’appelle `call_agent`, et il est fourni dans la compétence **« Delegate a Self-Contained Task to Another Agent »**, qui est aussi la meilleure documentation du procédé : lisez-la dans l’écran Compétences.',
      '',
      'La propriété importante : **l’autre agent ne voit rien de votre conversation.** Ni le message de l’utilisateur, ni vos outils, ni ce que vous avez trouvé. Le `message` que vous passez doit donc porter toute la demande : contexte, livrable, contraintes, format attendu.',
      '',
      'Des garde-fous qui gardent cela raisonnable :',
      '',
      '- La délégation peut descendre sur **3 agents de profondeur**. Deux agents qui s’appellent mutuellement s’arrêtent au lieu de boucler indéfiniment.',
      '- Une exécution déléguée reçoit un budget d’outils plus petit (**8 tours**) qu’une exécution lancée par une personne, car elle doit répondre dans le tour de son appelant.',
      '- Une exécution déléguée qui ne finit pas à temps renvoie une phrase qui l’explique, que l’appelant lit comme n’importe quel autre résultat d’outil.',
      '',
      'La délégation n’est pas un privilège : elle ne fait pas partie de l’administration système. Tout agent d’un projet peut utilement confier du travail à un autre, alors donnez la compétence à qui en a besoin.',
    ].join('\n'),
  },
  {
    id: 'chats',
    title: 'Chats et le panneau client',
    body: [
      'Un chat appartient à un utilisateur et à un projet. C’est son websocket qui pilote la boucle : le client envoie un message, et le serveur renvoie en flux les statuts, les indicateurs de frappe, les cartes d’outils et les réponses.',
      '',
      'Dans l’historique, vous verrez :',
      '',
      '- Le **message de l’utilisateur**, une fois.',
      '- Une **carte d’outil** par appel, avec l’entrée et la sortie : une mauvaise réponse peut ainsi être retracée jusqu’à l’appel qui l’a produite.',
      '- Des **messages de flux** : quand la sortie d’un agent devient l’entrée d’un autre, ce passage est enregistré aussi. Ils sont marqués comme flux au lieu d’être présentés comme tapés par une personne.',
      '- La **réponse de l’agent**.',
      '',
      'Une exécution peut être **arrêtée** en cours de route ; le chat redevient inactif et le travail partiel déjà enregistré reste dans l’historique.',
      '',
      '## Le panneau client',
      '',
      'Les clients voient **leurs propres projets et chats, et rien d’autre**. Ils ne voient ni les outils, ni les compétences, ni le flux de travail, ni les tables de stockage derrière ce qu’ils utilisent : seulement la conversation. Cette séparation est le but : un exploitant peut reconstruire tout l’étage agent en dessous sans que les utilisateurs remarquent autre chose que de meilleures réponses.',
    ].join('\n'),
  },
  {
    id: 'users-and-access',
    title: 'Utilisateurs, rôles et accès',
    body: [
      'Il y a deux rôles.',
      '',
      '| Rôle | Peut |',
      '| --- | --- |',
      '| `admin` | Tout : projets, agents, compétences, outils, stockage, utilisateurs, connexions LLM. Voit chaque chat. |',
      '| `client` | Ses propres projets et ses propres chats. Rien d’autre. |',
      '',
      'Les utilisateurs se créent dans **Utilisateurs** (ou par le Project Manager dans le chat). Un client n’atteint qu’un projet auquel il a été ajouté.',
      '',
      'Des règles d’accès à connaître :',
      '',
      '- **L’auto-inscription publique crée toujours un client.** Le rôle vient du serveur, jamais du corps de la requête ; sinon n’importe qui pourrait se fabriquer un compte administrateur.',
      '- **Les rôles élevés ne s’accordent que par les points d’accès d’administration.**',
      '- **Un chat appartient à son propriétaire.** Un non-administrateur ne peut pas publier dans le chat d’un autre, s’y abonner ni annuler son exécution.',
      '- **Une requête anonyme reçoit 401, un mauvais rôle 403.** Chaque routeur d’administration est protégé au niveau du routeur, donc aucun point d’accès isolé ne peut l’oublier.',
      '- **La connexion et l’inscription sont limitées en débit.**',
      '',
      '> Un administrateur *peut* publier dans le chat d’un client. Quand cela arrive, l’exécution agit quand même pour le propriétaire du chat : `user_id` dans un outil est le propriétaire, pas l’administrateur qui a écrit.',
    ].join('\n'),
  },
  {
    id: 'llm-connections',
    title: 'Connexions LLM',
    body: [
      'Le modèle sur lequel tourne tout le système est une ligne de la table `platforms`, pas une valeur dans un fichier de configuration. Changer de fournisseur, d’URL de base, de clé ou de modèle est donc une modification de données qu’un administrateur fait depuis le panneau plutôt qu’un déploiement.',
      '',
      '**Paramètres -> Connexions LLM** les gère. Chaque ligne contient :',
      '',
      '| Champ | Signification |',
      '| --- | --- |',
      '| Nom | Une étiquette, pour distinguer deux lignes |',
      '| URL de base | Le point d’accès de l’API (vide utilise la valeur par défaut du fournisseur) |',
      '| Clé d’API | Le secret, stocké et affiché tel que saisi |',
      '| Modèle | Le nom du modèle à demander |',
      '| Température | `0`–`2` ; vide laisse le fournisseur décider |',
      '| Tokens max | Plafond de la réponse ; vide signifie aucune limite |',
      '| Réflexion | Demander à un modèle de raisonnement de réfléchir avant de répondre |',
      '',
      '## Comment une connexion est choisie',
      '',
      '1. La ligne marquée **active** est utilisée.',
      '2. Si aucune n’est active, la **première** ligne est utilisée.',
      '3. Si la table est vide, les valeurs `DEEPSEEK_*` de `.env` sont utilisées : c’est l’état d’une installation toute neuve avant tout enregistrement.',
      '',
      'Exactement une ligne est active à la fois : en activer une retire la marque des autres. La bannière en haut de la page montre toujours quelle connexion s’applique réellement, vous n’avez donc jamais à appliquer vous-même la règle de repli.',
      '',
      '## Tester',
      '',
      '**Tester** fait un petit appel réel vers cette ligne et indique ce qui est revenu. C’est le moyen le plus rapide de vérifier une clé, une URL ou un nom de modèle — et cela vaut la peine d’appuyer après chaque modification, car une mauvaise connexion se manifeste sinon bien plus tard par une exécution en échec.',
      '',
      'Une modification enregistrée prend effet à l’**exécution suivante**, sans redémarrage. Les clients sont réutilisés tant que la configuration derrière eux n’a pas changé, donc changer de fournisseur ne jette pas les pools de connexions sans raison.',
      '',
      '> La clé d’API est stockée telle que saisie et renvoyée telle quelle : elle n’est pas masquée. L’écran Paramètres est réservé aux administrateurs exactement pour cette raison : qui peut lire la liste peut dépenser sur le compte derrière.',
    ].join('\n'),
  },  {
    id: 'system-project',
    title: 'Le projet System et le Project Manager',
    body: [
      'Un projet est particulier. Il est marqué `is_system`, ce qui signifie que sa propre ligne ne peut être ni renommée ni supprimée : l’agent qui y vit a donc toujours un chez-lui. Tout ce qu’il contient *à l’intérieur* reste modifiable, et c’est ce qui fait fonctionner l’arrangement.',
      '',
      'Il abrite l’agent **Project Manager**, qui porte la compétence **« System Administration »** et la compétence de délégation. Ses outils sont :',
      '',
      '| Outil | Ce qu’il gère |',
      '| --- | --- |',
      '| `manage_users` | Lister, lire, créer, mettre à jour, activer ou désactiver des utilisateurs |',
      '| `manage_projects` | Les projets, leurs membres, leurs agents et leur flux de travail |',
      '| `manage_agents` | Les agents et les compétences qu’ils portent |',
      '| `manage_skills` | Les compétences et les outils qu’elles portent |',
      '| `manage_tools` | Les outils, y compris la génération d’une spécification et d’un corps depuis une description |',
      '| `manage_storage` | Les tables de stockage, leurs colonnes et leurs lignes |',
      '| `call_agent` | Confier une tâche à un autre agent du projet |',
      '',
      'L’installation peut donc s’administrer **en le demandant dans le chat**. Créer un utilisateur, monter un projet, écrire un outil, câbler un flux de travail : le Project Manager le fait par la même couche de services que le panneau, pas par l’API REST.',
      '',
      'C’est aussi le moyen le plus rapide d’apprendre le système : demandez ce qui existe, et regardez quels appels d’outils reviennent.',
      '',
      'Des garde-fous à connaître : le Project Manager ne peut pas supprimer le projet System, ne peut pas s’en retirer, et ne peut pas se priver de son projet d’origine ni de ses propres compétences : vous ne pouvez donc pas vous enfermer hors de l’administration par accident.',
    ].join('\n'),
  },
  {
    id: 'use-cases',
    title: 'Cas d’usage',
    body: [
      'CerebrumKit est un point de départ : ce sont donc des formes, pas des produits finis. Chaque cas est la même mécanique avec une autre bibliothèque de stockage et un autre jeu d’outils.',
      '',
      '## 1. Un service de support qui répond à partir de vos propres données',
      '',
      'Le **stockage** contient `customers`, `orders` et `articles`. Les **outils** cherchent une commande par identifiant, trouvent un client par e-mail et parcourent les articles d’aide. Un agent de support porte une compétence qui lui dit : identifie d’abord le client, ne cite jamais une date de livraison que tu n’as pas lue dans la commande, et escalade tout ce qui touche à un remboursement.',
      '',
      'Le panneau client est votre boîte de support. Ce qui compte, ce sont les descriptions d’outils et le texte de la compétence, pas le modèle : un modèle ordinaire plus votre table de commandes bat un excellent modèle sans données.',
      '',
      '## 2. Une console d’exploitation au-dessus d’un système métier',
      '',
      'Vos vraies données vivent dans un autre système derrière une API HTTP. L’outil fourni **`api_call`** émet des requêtes ; écrivez des outils fins par point d’accès — `get_invoice`, `list_open_tickets`, `approve_leave` — pour que l’agent travaille avec des verbes nommés plutôt qu’avec des URL brutes.',
      '',
      'Deux agents enchaînés dans le flux de travail : un qui collecte et résume, un qui rédige l’action. Une personne lit le brouillon dans le chat avant que quoi que ce soit soit approuvé. D’abord des outils en lecture seule ; ajoutez les chemins d’écriture quand vous faites confiance aux descriptions.',
      '',
      '## 3. Vente interne : enquêter avant l’appel',
      '',
      'Un agent de recherche avec une compétence `web_search` et un outil `company_lookup` sur une table `accounts`. Son **outil de contexte** précharge la fiche du compte avant chaque message, donc « par quoi j’ouvre ? » se répond avec de vraies données au lieu d’être demandé.',
      '',
      'La délégation gagne ici sa place : l’agent principal confie « résume les deux derniers trimestres » à un agent de recherche et utilise la réponse, sans que le chercheur voie tout le fil.',
      '',
      '## 4. Saisie de documents au back-office',
      '',
      'Les opérateurs collent ou téléversent le texte extrait d’un document dans un chat. Les outils le confrontent aux tables de référence du stockage et proposent les écritures. Une file d’approbation n’est qu’un second projet dont l’agent a le droit d’écrire.',
      '',
      'L’import Excel d’une table de stockage est la façon dont les données de référence entrent ; l’export est la façon dont un relecteur emporte le résultat.',
      '',
      '## 5. Un assistant produit pour vos propres clients',
      '',
      'Un projet par client, chacun avec ses tables de stockage et ses agents, et des comptes client limités à leur projet. Le panneau d’administration est votre back-office ; le panneau client est le produit.',
      '',
      'Comme un client ne voit que ses propres chats et jamais les outils ni les tables derrière, vous pouvez reconstruire les compétences d’un agent entre deux sessions sans que le client remarque autre chose qu’un changement de réponses.',
      '',
      '## 6. Administrer la plateforme en lui parlant',
      '',
      'Même sans aucun domaine métier, le projet System est utile : demandez au Project Manager de créer un utilisateur, de monter un projet, d’écrire un outil à partir d’une description, de l’attacher à une compétence et de le câbler dans un flux de travail. Lisez ensuite les cartes d’outils dans l’historique pour voir exactement ce qu’il a fait.',
      '',
      'Pour quiconque apprend le système, c’est la visite la plus rapide possible — et c’est un exemple fonctionnel de toute la conception.',
    ].join('\n'),
  },
  {
    id: 'security',
    title: 'Sécurité et confiance',
    body: [
      'Le modèle de confiance mérite d’être énoncé clairement, car deux de ses propriétés sont délibérées et l’une d’elles est tranchante.',
      '',
      '## Un corps d’outil, c’est de l’exécution de code',
      '',
      'Les corps d’outils sont compilés et exécutés avec tous les builtins. Ils ne sont **pas isolés**, car les outils fournis importent `requests`, SQLAlchemy et des éléments internes de l’application, et l’un d’eux passe à la base du SQL écrit par le modèle : un bac à sable aux builtins restreints les casserait tous.',
      '',
      'Donc : écrire un outil équivaut à exécuter du code sur le serveur. Les points d’accès d’outils doivent rester réservés aux administrateurs, et `tools.body` doit être relu comme vous reliriez un commit. C’est aussi pourquoi le bouton **Générer** rédige un corps mais ne l’installe pas en silence.',
      '',
      'Un appelant ne peut toujours pas atteindre un outil qui n’est pas attaché à son agent, et le modèle ne peut pas fournir de `project_id` au corps d’un outil : le serveur fournit les identifiants de l’exécution.',
      '',
      '## Contrôle d’accès',
      '',
      '| Règle | Où elle s’applique |',
      '| --- | --- |',
      '| Les routeurs d’administration sont réservés aux administrateurs | Dépendance au niveau du routeur, aucun point d’accès ne peut l’oublier |',
      '| L’inscription ne peut pas créer un administrateur | Le rôle est fixé côté serveur, jamais lu dans le corps |',
      '| Un chat appartient à son propriétaire | Vérifié sur les routes REST et de nouveau sur le websocket |',
      '| L’historique n’est pas lisible entre utilisateurs | Les non-administrateurs sont toujours filtrés sur leurs propres lignes |',
      '| Connexion et inscription limitées en débit | Limiteur à fenêtre glissante par client |',
      '',
      '## Secrets',
      '',
      '- Les clés d’API LLM sont stockées en base et affichées **sans masque** dans les Paramètres, réservés aux administrateurs par conception.',
      '- `SECRET_KEY` signe les JWT. L’application avertit au démarrage si elle est restée à la valeur d’exemple : changez-la avant que quelqu’un d’autre atteigne l’installation.',
      '- Les comptes fournis ont des mots de passe fournis. Changez-les.',
      '- `.env` n’est pas versionné. Gardez-le ainsi.',
      '',
      '## Là où la sortie du modèle est traitée comme non fiable',
      '',
      '- L’export de feuille de calcul neutralise l’injection de formules : une cellule commençant par `=` ne peut pas s’exécuter dans Excel.',
      '- Les résultats d’outils sont tronqués avant d’atteindre le modèle, et rognés à l’intérieur de leur JSON plutôt que coupés.',
      '- Les exécutions sont plafonnées en étapes, en tours d’outils, en profondeur de délégation et en durée d’outil : aucune exécution ne peut tourner sans fin.',
    ].join('\n'),
  },
  {
    id: 'operations',
    title: 'Exploitation',
    body: [
      '## Le lancer',
      '',
      '```bash',
      '# backend',
      'cd backend && venv/Scripts/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8000',
      '',
      '# frontend',
      'cd frontend/cerebrumkit-vue && npm run dev',
      '```',
      '',
      'Sous Windows, `run.ps1` démarre les deux et `stop.ps1` les arrête. Pour la production, `DEPLOY.md` couvre nginx, systemd et un chemin de reconstruction qui garde les lignes de la base (outils, compétences, agents) au même pas que le code.',
      '',
      '## Modifications de la base',
      '',
      '`backend/migrate.py` crée les tables manquantes et ajoute les colonnes manquantes. On peut le relancer sans risque : c’est ainsi qu’on monte une nouvelle installation, et qu’un nouveau modèle dans `backend/app/models/` devient une table.',
      '',
      '## Alimentation',
      '',
      '| Script | Ce qu’il fait |',
      '| --- | --- |',
      '| `seed_all.py` | Tout ce qui suit, dans l’ordre — la seule commande dont une installation neuve a besoin |',
      '| `seed.py` | Les comptes admin et client à partir des variables `SEED_*` |',
      '| `seed_countries.py` | La liste des pays |',
      '| `seed_general_tools.py` | Les outils généraux et leurs compétences |',
      '| `seed_system_project.py` | Le projet System et le Project Manager |',
      '',
      'Tous sont idempotents — les lignes sont appariées par nom et mises à jour sur place — donc les relancer après avoir modifié un corps d’outil pousse la correction.',
      '',
      '## Déplacer des données entre installations',
      '',
      '`export_for_deploy.py` écrit les données du projet et `load_for_deploy.py` les relit. Utilisez-les pour déplacer outils, compétences, agents et définitions de stockage d’une installation de développement vers une installation déployée.',
      '',
      '## Journaux',
      '',
      'L’assistant `run.ps1` écrit `backend.log` / `backend.err.log` et `frontend.log` / `frontend.err.log` à côté de la racine du projet. Une exécution en échec est journalisée avec l’identifiant du chat, donc un signalement « il n’a pas répondu » peut être retracé jusqu’à l’exécution qui a échoué.',
      '',
      '## Déployer une modification d’agent',
      '',
      'La plupart des modifications d’agents ne demandent aucun déploiement : modifiez l’outil, la compétence ou l’agent dans le panneau et cela prend effet à l’exécution suivante. Vous ne redéployez que lorsque le **code** change : la boucle d’agent, un routeur, un modèle.',
    ].join('\n'),
  },
  {
    id: 'reference',
    title: 'Référence',
    body: [
      '## Limites',
      '',
      'Chaque plafond existe pour qu’une exécution emballée ne consomme pas le système. Ils sont dans `backend/app/core/agent_loop.py`.',
      '',
      '| Limite | Valeur | Pourquoi |',
      '| --- | --- | --- |',
      '| Tours d’appels d’outils par tour d’agent | 100 | Empêche un modèle de boucler sur les appels d’outils |',
      '| Tours d’appels dans une exécution déléguée | 8 | Elle doit répondre dans le tour de son appelant |',
      '| Profondeur de délégation | 3 | Deux agents qui s’appellent mutuellement s’arrêtent |',
      '| Délai d’un appel d’outil | 60 s | Un outil qui ne revient jamais ne peut pas bloquer l’exécution |',
      '| Délai d’un appel délégué | 300 s | Une exécution imbriquée a besoin de plus qu’un outil normal |',
      '| Résultat d’outil transmis au modèle | 8 000 caractères | Une grosse réponse d’API ne peut pas manger la fenêtre de contexte |',
      '| Carte d’outil conservée dans le chat | 100 000 caractères | La carte est pour une personne, et reste bornée |',
      '| Outils de contexte préalables, total | 24 000 caractères | Garde le prompt système proportionné |',
      '| Dernière réponse de l’agent injectée | 2 000 caractères | Assez pour la conclusion, pas pour une page entière de JSON |',
      '| Étapes de flux de travail par exécution | 200 | Filet de sécurité contre un flux mal formé ou cyclique |',
      '| Messages antérieurs du chat envoyés à l’agent | 0 | Les faits sont portés par les outils et la mémoire, pas par l’historique |',
      '| Délai d’un appel au modèle | 180 s | Par appel, par agent |',
      '',
      '## Tables',
      '',
      '| Table | Contient |',
      '| --- | --- |',
      '| `users` | Comptes, rôles, langue, pays |',
      '| `projects` | Les projets, leur JSON de flux de travail et l’indicateur `is_system` |',
      '| `agents` | Les agents et leurs descriptions |',
      '| `skills` | Les compétences et leur texte d’instructions |',
      '| `tools` | Les outils : spécification de fonction (`description`) et corps Python (`body`) |',
      '| `agent_skill`, `skill_tool` | Quelles compétences a un agent, quels outils a une compétence |',
      '| `user_project`, `agent_project` | L’appartenance à un projet |',
      '| `agent_context_tools` | Les outils préalables, leurs titres et leurs arguments |',
      '| `chats`, `messages` | Les conversations et chaque message, cartes d’outils comprises |',
      '| `memory` | Les notes indexées par (agent, utilisateur) |',
      '| `project_tables` | Quelles tables de stockage possède un projet |',
      '| `platforms` | Les connexions LLM et laquelle est active |',
      '| `countries` | La liste des pays |',
      '',
      'Les tables que vous créez dans **Stockage** sont aussi de vraies tables et apparaissent ici aux côtés des précédentes.',
      '',
      '## Où vit chaque chose',
      '',
      '```text',
      'backend/app/core/       boucle d’agent, exécution d’outils, délégation, client LLM, auth',
      'backend/app/models/     modèles SQLAlchemy',
      'backend/app/routers/    API REST + websocket',
      'backend/app/schemas/    modèles de requête et de réponse',
      'backend/app/system_management.py   les outils manage_* du Project Manager',
      'frontend/.../views/admin/    Projets, Compétences, Outils, Stockage, Utilisateurs, Paramètres, Documentation',
      'frontend/.../views/client/   Projets et le chat avec les agents',
      'frontend/.../locales/        en, zh, ru, es, fr, de',
      '```',
      '',
      '## Ajouter un domaine métier',
      '',
      'Ajoutez des modèles dans `backend/app/models/`, enregistrez-les dans `app/models/__init__.py`, ajoutez routeurs et schémas de la même façon, et créez les tables avec `backend/migrate.py`.',
      '',
      'Mais préférez la bibliothèque de stockage. Tout ce dont un projet a besoin à l’exécution est mieux en **outil au-dessus du stockage**, car les personnes qui possèdent le projet peuvent alors le modifier sans déploiement : c’est toute la raison pour laquelle les outils et les compétences vivent en base.',
    ].join('\n'),
  },
]